"""Expansion data for the camera/lens reference catalog: 1980-present.

Film and digital bodies plus notable lenses from the major manufacturers.
Imported by camera_catalog.py and appended to its CATALOG list, so the
generic reference dialog and suggestion panel pick these up automatically.

Text-only, same entry shape as camera_catalog.CATALOG.
"""

from __future__ import annotations
from typing import List, Dict, Any

EXPANSION: List[Dict[str, Any]] = [

    # ── Canon film SLRs (1980s-2000s) ────────────────────────────────────────
    {"title": "Canon A-1",                 "make": "Canon",    "year": "1978-1985", "type": "SLR (film)", "format": "35mm Film", "mount": "Canon FD", "category": "Camera", "notes": "First SLR with full program AE. Black-only body."},
    {"title": "Canon AV-1",                "make": "Canon",    "year": "1979-1983", "type": "SLR (film)", "format": "35mm Film", "mount": "Canon FD", "category": "Camera", "notes": "Aperture-priority companion to the AE-1."},
    {"title": "Canon AL-1",                "make": "Canon",    "year": "1982-1985", "type": "SLR (film)", "format": "35mm Film", "mount": "Canon FD", "category": "Camera", "notes": "Quick Focus electronic focus assist."},
    {"title": "Canon T50",                 "make": "Canon",    "year": "1983-1989", "type": "SLR (film)", "format": "35mm Film", "mount": "Canon FD", "category": "Camera", "notes": "Entry-level program-only T series."},
    {"title": "Canon T70",                 "make": "Canon",    "year": "1984-1987", "type": "SLR (film)", "format": "35mm Film", "mount": "Canon FD", "category": "Camera", "notes": "Multi-program AE, LCD top panel."},
    {"title": "Canon T90",                 "make": "Canon",    "year": "1986-1991", "type": "SLR (film)", "format": "35mm Film", "mount": "Canon FD", "category": "Camera", "notes": "Luigi Colani design; last pro FD body. Nicknamed 'The Tank'. Influenced all later EOS ergonomics."},
    {"title": "Canon EOS 650",             "make": "Canon",    "year": "1987-1989", "type": "SLR (film)", "format": "35mm Film", "mount": "Canon EF", "category": "Camera", "notes": "First EOS camera; launched the EF mount."},
    {"title": "Canon EOS 620",             "make": "Canon",    "year": "1987-1989", "type": "SLR (film)", "format": "35mm Film", "mount": "Canon EF", "category": "Camera", "notes": "Higher-spec 650 with 1/4000s."},
    {"title": "Canon EOS RT",              "make": "Canon",    "year": "1989-1992", "type": "SLR (film)", "format": "35mm Film", "mount": "Canon EF", "category": "Camera", "notes": "Fixed pellicle mirror; no viewfinder blackout."},
    {"title": "Canon EOS-1",               "make": "Canon",    "year": "1989-1994", "type": "SLR (film)", "format": "35mm Film", "mount": "Canon EF", "category": "Camera", "notes": "First professional EOS body."},
    {"title": "Canon EOS 10s",             "make": "Canon",    "year": "1990-1993", "type": "SLR (film)", "format": "35mm Film", "mount": "Canon EF", "category": "Camera", "notes": "Barcode program reader accessory."},
    {"title": "Canon EOS Elan (100)",      "make": "Canon",    "year": "1991-1995", "type": "SLR (film)", "format": "35mm Film", "mount": "Canon EF", "category": "Camera", "notes": "Quiet film transport mid-range body."},
    {"title": "Canon EOS A2 / A2e (5)",    "make": "Canon",    "year": "1992-1998", "type": "SLR (film)", "format": "35mm Film", "mount": "Canon EF", "category": "Camera", "notes": "A2e had eye-controlled focus."},
    {"title": "Canon EOS-1N",              "make": "Canon",    "year": "1994-2000", "type": "SLR (film)", "format": "35mm Film", "mount": "Canon EF", "category": "Camera", "notes": "Pro workhorse of the 1990s; 16 custom functions."},
    {"title": "Canon EOS Rebel G (500N)",  "make": "Canon",    "year": "1996-1999", "type": "SLR (film)", "format": "35mm Film", "mount": "Canon EF", "category": "Camera", "notes": "Hugely common student film body."},
    {"title": "Canon EOS-3",               "make": "Canon",    "year": "1998-2007", "type": "SLR (film)", "format": "35mm Film", "mount": "Canon EF", "category": "Camera", "notes": "45-point eye-controlled AF; near-pro spec."},
    {"title": "Canon EOS Elan 7 (30/33)",  "make": "Canon",    "year": "2000-2004", "type": "SLR (film)", "format": "35mm Film", "mount": "Canon EF", "category": "Camera", "notes": "Whisper-quiet drive; late film era."},

    # ── Canon DSLRs ──────────────────────────────────────────────────────────
    {"title": "Canon EOS D30",             "make": "Canon",    "year": "2000-2002", "type": "DSLR", "format": "APS-C", "mount": "Canon EF", "category": "Camera", "notes": "Canon's first in-house DSLR sensor; 3.1MP CMOS."},
    {"title": "Canon EOS D60",             "make": "Canon",    "year": "2002-2003", "type": "DSLR", "format": "APS-C", "mount": "Canon EF", "category": "Camera", "notes": "6.3MP follow-up to the D30."},
    {"title": "Canon EOS 10D",             "make": "Canon",    "year": "2003-2004", "type": "DSLR", "format": "APS-C", "mount": "Canon EF", "category": "Camera", "notes": "Magnesium body enthusiast DSLR."},
    {"title": "Canon EOS Digital Rebel (300D)", "make": "Canon", "year": "2003-2005", "type": "DSLR", "format": "APS-C", "mount": "Canon EF/EF-S", "category": "Camera", "notes": "First sub-$1000 DSLR; mass-market breakthrough."},
    {"title": "Canon EOS 20D",             "make": "Canon",    "year": "2004-2006", "type": "DSLR", "format": "APS-C", "mount": "Canon EF/EF-S", "category": "Camera", "notes": "8.2MP, 5fps; hugely popular."},
    {"title": "Canon EOS 5D (original)",   "make": "Canon",    "year": "2005-2008", "type": "DSLR", "format": "35mm Full Frame", "mount": "Canon EF", "category": "Camera", "notes": "First 'affordable' full-frame DSLR; classic 12.8MP rendering."},
    {"title": "Canon EOS 30D",             "make": "Canon",    "year": "2006-2007", "type": "DSLR", "format": "APS-C", "mount": "Canon EF/EF-S", "category": "Camera", "notes": ""},
    {"title": "Canon EOS 40D",             "make": "Canon",    "year": "2007-2008", "type": "DSLR", "format": "APS-C", "mount": "Canon EF/EF-S", "category": "Camera", "notes": "10MP, live view."},
    {"title": "Canon EOS 1D Mark II",      "make": "Canon",    "year": "2004-2007", "type": "DSLR", "format": "APS-H", "mount": "Canon EF", "category": "Camera", "notes": "8.5fps sports flagship."},
    {"title": "Canon EOS-1Ds Mark II",     "make": "Canon",    "year": "2004-2007", "type": "DSLR", "format": "35mm Full Frame", "mount": "Canon EF", "category": "Camera", "notes": "16.7MP studio flagship."},
    {"title": "Canon EOS-1D X",            "make": "Canon",    "year": "2012-2016", "type": "DSLR", "format": "35mm Full Frame", "mount": "Canon EF", "category": "Camera", "notes": "Merged 1D/1Ds lines; 12fps."},
    {"title": "Canon EOS-1D X Mark III",   "make": "Canon",    "year": "2020-2023", "type": "DSLR", "format": "35mm Full Frame", "mount": "Canon EF", "category": "Camera", "notes": "Final Canon pro DSLR."},
    {"title": "Canon EOS 7D",              "make": "Canon",    "year": "2009-2014", "type": "DSLR", "format": "APS-C", "mount": "Canon EF/EF-S", "category": "Camera", "notes": "8fps APS-C flagship; loved for sports/wildlife."},
    {"title": "Canon EOS 7D Mark II",      "make": "Canon",    "year": "2014-2020", "type": "DSLR", "format": "APS-C", "mount": "Canon EF/EF-S", "category": "Camera", "notes": "10fps, 65 cross-type AF points."},
    {"title": "Canon EOS 5D Mark III",     "make": "Canon",    "year": "2012-2016", "type": "DSLR", "format": "35mm Full Frame", "mount": "Canon EF", "category": "Camera", "notes": "22MP all-rounder; fixed the Mark II's AF."},
    {"title": "Canon EOS 5D Mark IV",      "make": "Canon",    "year": "2016-2021", "type": "DSLR", "format": "35mm Full Frame", "mount": "Canon EF", "category": "Camera", "notes": "30MP, Dual Pixel AF."},
    {"title": "Canon EOS 5DS / 5DS R",     "make": "Canon",    "year": "2015-2020", "type": "DSLR", "format": "35mm Full Frame", "mount": "Canon EF", "category": "Camera", "notes": "50.6MP high-resolution variants."},
    {"title": "Canon EOS 6D",              "make": "Canon",    "year": "2012-2017", "type": "DSLR", "format": "35mm Full Frame", "mount": "Canon EF", "category": "Camera", "notes": "Budget full frame with GPS/Wi-Fi."},
    {"title": "Canon EOS 6D Mark II",      "make": "Canon",    "year": "2017-2023", "type": "DSLR", "format": "35mm Full Frame", "mount": "Canon EF", "category": "Camera", "notes": "26MP, vari-angle screen."},
    {"title": "Canon EOS 90D",             "make": "Canon",    "year": "2019-present", "type": "DSLR", "format": "APS-C", "mount": "Canon EF/EF-S", "category": "Camera", "notes": "32.5MP; last enthusiast Canon DSLR."},
    {"title": "Canon EOS Rebel T3i (600D)","make": "Canon",    "year": "2011-2016", "type": "DSLR", "format": "APS-C", "mount": "Canon EF/EF-S", "category": "Camera", "notes": "Massive seller; articulating screen."},

    # ── Canon mirrorless ─────────────────────────────────────────────────────
    {"title": "Canon EOS M50",             "make": "Canon",    "year": "2018-2023", "type": "Mirrorless", "format": "APS-C", "mount": "Canon EF-M", "category": "Camera", "notes": "Best-selling EF-M body; vlogging favorite."},
    {"title": "Canon EOS R",               "make": "Canon",    "year": "2018-2022", "type": "Mirrorless", "format": "35mm Full Frame", "mount": "Canon RF", "category": "Camera", "notes": "First RF-mount body; 30MP."},
    {"title": "Canon EOS RP",              "make": "Canon",    "year": "2019-present", "type": "Mirrorless", "format": "35mm Full Frame", "mount": "Canon RF", "category": "Camera", "notes": "Smallest, cheapest full-frame RF."},
    {"title": "Canon EOS R6",              "make": "Canon",    "year": "2020-2022", "type": "Mirrorless", "format": "35mm Full Frame", "mount": "Canon RF", "category": "Camera", "notes": "20MP, exceptional IBIS and AF."},
    {"title": "Canon EOS R6 Mark II",      "make": "Canon",    "year": "2022-present", "type": "Mirrorless", "format": "35mm Full Frame", "mount": "Canon RF", "category": "Camera", "notes": "24MP, 40fps electronic."},
    {"title": "Canon EOS R3",              "make": "Canon",    "year": "2021-present", "type": "Mirrorless", "format": "35mm Full Frame", "mount": "Canon RF", "category": "Camera", "notes": "Eye-control AF returns; stacked sensor."},
    {"title": "Canon EOS R7",              "make": "Canon",    "year": "2022-present", "type": "Mirrorless", "format": "APS-C", "mount": "Canon RF", "category": "Camera", "notes": "32.5MP APS-C flagship."},
    {"title": "Canon EOS R8",              "make": "Canon",    "year": "2023-present", "type": "Mirrorless", "format": "35mm Full Frame", "mount": "Canon RF", "category": "Camera", "notes": "Light full-frame; R6 II sensor."},
    {"title": "Canon EOS R10",             "make": "Canon",    "year": "2022-present", "type": "Mirrorless", "format": "APS-C", "mount": "Canon RF", "category": "Camera", "notes": "Entry APS-C RF."},

    # ── Nikon film SLRs (1980s-2000s) ────────────────────────────────────────
    {"title": "Nikon EM",                  "make": "Nikon",    "year": "1979-1984", "type": "SLR (film)", "format": "35mm Film", "mount": "Nikon F", "category": "Camera", "notes": "Compact aperture-priority body."},
    {"title": "Nikon FG",                  "make": "Nikon",    "year": "1982-1986", "type": "SLR (film)", "format": "35mm Film", "mount": "Nikon F", "category": "Camera", "notes": "First Nikon with program mode."},
    {"title": "Nikon FA",                  "make": "Nikon",    "year": "1983-1988", "type": "SLR (film)", "format": "35mm Film", "mount": "Nikon F", "category": "Camera", "notes": "First matrix (AMP) metering camera; 'Technical Camera of the Year' 1984."},
    {"title": "Nikon FM3A",                "make": "Nikon",    "year": "2001-2006", "type": "SLR (film)", "format": "35mm Film", "mount": "Nikon F", "category": "Camera", "notes": "Hybrid mechanical/electronic shutter; the last great manual-focus Nikon. Highly collectible."},
    {"title": "Nikon N90s (F90X)",         "make": "Nikon",    "year": "1994-2001", "type": "SLR (film)", "format": "35mm Film", "mount": "Nikon F", "category": "Camera", "notes": "Fast AF workhorse of the 90s."},
    {"title": "Nikon F100",                "make": "Nikon",    "year": "1999-2006", "type": "SLR (film)", "format": "35mm Film", "mount": "Nikon F", "category": "Camera", "notes": "'Baby F5'; possibly the best value pro film Nikon today."},
    {"title": "Nikon F6",                  "make": "Nikon",    "year": "2004-2020", "type": "SLR (film)", "format": "35mm Film", "mount": "Nikon F", "category": "Camera", "notes": "The last 35mm film SLR in production by anyone."},
    {"title": "Nikon N80 (F80)",           "make": "Nikon",    "year": "2000-2006", "type": "SLR (film)", "format": "35mm Film", "mount": "Nikon F", "category": "Camera", "notes": "Popular late film-era enthusiast body."},
    {"title": "Nikon 35Ti",                "make": "Nikon",    "year": "1993-1998", "type": "Point & Shoot", "format": "35mm Film", "mount": "Fixed (35mm f/2.8)", "category": "Camera", "notes": "Titanium compact with analog gauge top; cult collectible."},
    {"title": "Nikon 28Ti",                "make": "Nikon",    "year": "1994-1998", "type": "Point & Shoot", "format": "35mm Film", "mount": "Fixed (28mm f/2.8)", "category": "Camera", "notes": "Black titanium sibling of the 35Ti."},

    # ── Nikon DSLRs ──────────────────────────────────────────────────────────
    {"title": "Nikon D1X",                 "make": "Nikon",    "year": "2001-2004", "type": "DSLR", "format": "APS-C", "mount": "Nikon F", "category": "Camera", "notes": "5.3MP studio variant of the D1."},
    {"title": "Nikon D100",                "make": "Nikon",    "year": "2002-2005", "type": "DSLR", "format": "APS-C", "mount": "Nikon F", "category": "Camera", "notes": "6MP enthusiast body."},
    {"title": "Nikon D70",                 "make": "Nikon",    "year": "2004-2006", "type": "DSLR", "format": "APS-C", "mount": "Nikon F", "category": "Camera", "notes": "Answer to the Digital Rebel; 1/500s flash sync."},
    {"title": "Nikon D200",                "make": "Nikon",    "year": "2005-2008", "type": "DSLR", "format": "APS-C", "mount": "Nikon F", "category": "Camera", "notes": "10MP magnesium semi-pro."},
    {"title": "Nikon D2X",                 "make": "Nikon",    "year": "2005-2007", "type": "DSLR", "format": "APS-C", "mount": "Nikon F", "category": "Camera", "notes": "12.4MP pro flagship before the D3."},
    {"title": "Nikon D300",                "make": "Nikon",    "year": "2007-2009", "type": "DSLR", "format": "APS-C", "mount": "Nikon F", "category": "Camera", "notes": "Legendary APS-C pro body; 51-point AF."},
    {"title": "Nikon D700",                "make": "Nikon",    "year": "2008-2012", "type": "DSLR", "format": "35mm Full Frame", "mount": "Nikon F", "category": "Camera", "notes": "D3 sensor in a smaller body; still beloved."},
    {"title": "Nikon D90",                 "make": "Nikon",    "year": "2008-2010", "type": "DSLR", "format": "APS-C", "mount": "Nikon F", "category": "Camera", "notes": "First DSLR with video recording."},
    {"title": "Nikon D7000",               "make": "Nikon",    "year": "2010-2013", "type": "DSLR", "format": "APS-C", "mount": "Nikon F", "category": "Camera", "notes": "16MP dual-card enthusiast hit."},
    {"title": "Nikon D800 / D800E",        "make": "Nikon",    "year": "2012-2014", "type": "DSLR", "format": "35mm Full Frame", "mount": "Nikon F", "category": "Camera", "notes": "36MP resolution milestone."},
    {"title": "Nikon D600 / D610",         "make": "Nikon",    "year": "2012-2019", "type": "DSLR", "format": "35mm Full Frame", "mount": "Nikon F", "category": "Camera", "notes": "24MP entry full frame."},
    {"title": "Nikon D4 / D4S",            "make": "Nikon",    "year": "2012-2016", "type": "DSLR", "format": "35mm Full Frame", "mount": "Nikon F", "category": "Camera", "notes": "16MP pro sports bodies."},
    {"title": "Nikon D750",                "make": "Nikon",    "year": "2014-2020", "type": "DSLR", "format": "35mm Full Frame", "mount": "Nikon F", "category": "Camera", "notes": "Hugely popular wedding/event body."},
    {"title": "Nikon D810",                "make": "Nikon",    "year": "2014-2017", "type": "DSLR", "format": "35mm Full Frame", "mount": "Nikon F", "category": "Camera", "notes": "Refined 36MP; base ISO 64."},
    {"title": "Nikon D500",                "make": "Nikon",    "year": "2016-2022", "type": "DSLR", "format": "APS-C", "mount": "Nikon F", "category": "Camera", "notes": "10fps APS-C flagship; D5 AF system."},
    {"title": "Nikon D5",                  "make": "Nikon",    "year": "2016-2020", "type": "DSLR", "format": "35mm Full Frame", "mount": "Nikon F", "category": "Camera", "notes": "153-point AF pro flagship."},
    {"title": "Nikon D850",                "make": "Nikon",    "year": "2017-present", "type": "DSLR", "format": "35mm Full Frame", "mount": "Nikon F", "category": "Camera", "notes": "45.7MP BSI; widely called the greatest DSLR ever made."},
    {"title": "Nikon D6",                  "make": "Nikon",    "year": "2020-2023", "type": "DSLR", "format": "35mm Full Frame", "mount": "Nikon F", "category": "Camera", "notes": "Final Nikon pro DSLR."},

    # ── Nikon mirrorless ─────────────────────────────────────────────────────
    {"title": "Nikon Z7",                  "make": "Nikon",    "year": "2018-2020", "type": "Mirrorless", "format": "35mm Full Frame", "mount": "Nikon Z", "category": "Camera", "notes": "45.7MP launch flagship of the Z mount."},
    {"title": "Nikon Z5",                  "make": "Nikon",    "year": "2020-present", "type": "Mirrorless", "format": "35mm Full Frame", "mount": "Nikon Z", "category": "Camera", "notes": "Entry full-frame Z."},
    {"title": "Nikon Z6 II / Z7 II",       "make": "Nikon",    "year": "2020-2024", "type": "Mirrorless", "format": "35mm Full Frame", "mount": "Nikon Z", "category": "Camera", "notes": "Dual processors, dual card slots."},
    {"title": "Nikon Z50",                 "make": "Nikon",    "year": "2019-present", "type": "Mirrorless", "format": "APS-C", "mount": "Nikon Z", "category": "Camera", "notes": "First DX Z body."},
    {"title": "Nikon Z fc",                "make": "Nikon",    "year": "2021-present", "type": "Mirrorless", "format": "APS-C", "mount": "Nikon Z", "category": "Camera", "notes": "FM2-styled retro DX."},
    {"title": "Nikon Z8",                  "make": "Nikon",    "year": "2023-present", "type": "Mirrorless", "format": "35mm Full Frame", "mount": "Nikon Z", "category": "Camera", "notes": "Z9 stacked sensor in a smaller body."},
    {"title": "Nikon Zf",                  "make": "Nikon",    "year": "2023-present", "type": "Mirrorless", "format": "35mm Full Frame", "mount": "Nikon Z", "category": "Camera", "notes": "Full-frame retro body recalling the FM/FE."},

    # ── Sony / Minolta ───────────────────────────────────────────────────────
    {"title": "Minolta Maxxum 9000",       "make": "Minolta",  "year": "1985-1990", "type": "SLR (film)", "format": "35mm Film", "mount": "Minolta A", "category": "Camera", "notes": "Pro AF body; manual film advance."},
    {"title": "Minolta Maxxum 7 (Dynax 7)","make": "Minolta",  "year": "2000-2006", "type": "SLR (film)", "format": "35mm Film", "mount": "Minolta A", "category": "Camera", "notes": "Brilliant late film body; rear LCD nav."},
    {"title": "Minolta TC-1",              "make": "Minolta",  "year": "1996-2005", "type": "Point & Shoot", "format": "35mm Film", "mount": "Fixed (G-Rokkor 28mm f/3.5)", "category": "Camera", "notes": "Smallest titanium 35mm compact; cult G-Rokkor lens."},
    {"title": "Minolta Maxxum 7D",         "make": "Minolta",  "year": "2004-2006", "type": "DSLR", "format": "APS-C", "mount": "Minolta A", "category": "Camera", "notes": "First DSLR with in-body stabilization."},
    {"title": "Sony Alpha A100",           "make": "Sony",     "year": "2006-2008", "type": "DSLR", "format": "APS-C", "mount": "Sony A", "category": "Camera", "notes": "Sony's first DSLR after buying Konica Minolta."},
    {"title": "Sony Alpha A700",           "make": "Sony",     "year": "2007-2009", "type": "DSLR", "format": "APS-C", "mount": "Sony A", "category": "Camera", "notes": "Enthusiast A-mount."},
    {"title": "Sony Alpha A900",           "make": "Sony",     "year": "2008-2011", "type": "DSLR", "format": "35mm Full Frame", "mount": "Sony A", "category": "Camera", "notes": "24.6MP; Sony's first full frame."},
    {"title": "Sony NEX-5",                "make": "Sony",     "year": "2010-2012", "type": "Mirrorless", "format": "APS-C", "mount": "Sony E", "category": "Camera", "notes": "Tiny early E-mount body."},
    {"title": "Sony NEX-7",                "make": "Sony",     "year": "2011-2014", "type": "Mirrorless", "format": "APS-C", "mount": "Sony E", "category": "Camera", "notes": "24MP Tri-Navi enthusiast NEX."},
    {"title": "Sony A7 (original)",        "make": "Sony",     "year": "2013-2015", "type": "Mirrorless", "format": "35mm Full Frame", "mount": "Sony E", "category": "Camera", "notes": "First full-frame mirrorless with AF; reshaped the industry."},
    {"title": "Sony A7R",                  "make": "Sony",     "year": "2013-2015", "type": "Mirrorless", "format": "35mm Full Frame", "mount": "Sony E", "category": "Camera", "notes": "36MP no-AA-filter launch sibling."},
    {"title": "Sony A7S",                  "make": "Sony",     "year": "2014-2016", "type": "Mirrorless", "format": "35mm Full Frame", "mount": "Sony E", "category": "Camera", "notes": "12MP low-light/video monster."},
    {"title": "Sony A7 II",                "make": "Sony",     "year": "2014-2018", "type": "Mirrorless", "format": "35mm Full Frame", "mount": "Sony E", "category": "Camera", "notes": "First full-frame 5-axis IBIS."},
    {"title": "Sony A7R II",               "make": "Sony",     "year": "2015-2017", "type": "Mirrorless", "format": "35mm Full Frame", "mount": "Sony E", "category": "Camera", "notes": "42MP BSI breakthrough."},
    {"title": "Sony A7 III",               "make": "Sony",     "year": "2018-2021", "type": "Mirrorless", "format": "35mm Full Frame", "mount": "Sony E", "category": "Camera", "notes": "The 'basic model' that outsold everything."},
    {"title": "Sony A7R III / A7R IV",     "make": "Sony",     "year": "2017-2022", "type": "Mirrorless", "format": "35mm Full Frame", "mount": "Sony E", "category": "Camera", "notes": "42MP then 61MP resolution leaders."},
    {"title": "Sony A7S III",              "make": "Sony",     "year": "2020-present", "type": "Mirrorless", "format": "35mm Full Frame", "mount": "Sony E", "category": "Camera", "notes": "4K120 video standard-bearer."},
    {"title": "Sony A7 IV",                "make": "Sony",     "year": "2021-present", "type": "Mirrorless", "format": "35mm Full Frame", "mount": "Sony E", "category": "Camera", "notes": "33MP hybrid all-rounder."},
    {"title": "Sony A9",                   "make": "Sony",     "year": "2017-2019", "type": "Mirrorless", "format": "35mm Full Frame", "mount": "Sony E", "category": "Camera", "notes": "First stacked-sensor sports body; blackout-free 20fps."},
    {"title": "Sony A1",                   "make": "Sony",     "year": "2021-present", "type": "Mirrorless", "format": "35mm Full Frame", "mount": "Sony E", "category": "Camera", "notes": "50MP 30fps 8K flagship."},
    {"title": "Sony A6000",                "make": "Sony",     "year": "2014-2019", "type": "Mirrorless", "format": "APS-C", "mount": "Sony E", "category": "Camera", "notes": "One of the best-selling mirrorless cameras ever."},
    {"title": "Sony A6400 / A6600",        "make": "Sony",     "year": "2019-present", "type": "Mirrorless", "format": "APS-C", "mount": "Sony E", "category": "Camera", "notes": "Real-time tracking AF APS-C line."},
    {"title": "Sony A7C",                  "make": "Sony",     "year": "2020-present", "type": "Mirrorless", "format": "35mm Full Frame", "mount": "Sony E", "category": "Camera", "notes": "Rangefinder-style compact full frame."},
    {"title": "Sony RX1 / RX1R",           "make": "Sony",     "year": "2012-2017", "type": "Point & Shoot", "format": "35mm Full Frame", "mount": "Fixed (Zeiss 35mm f/2)", "category": "Camera", "notes": "Full-frame fixed-lens compact."},
    {"title": "Sony RX100 series",         "make": "Sony",     "year": "2012-present", "type": "Point & Shoot", "format": "1\"", "mount": "Fixed zoom", "category": "Camera", "notes": "Defined the premium 1-inch compact; seven generations."},

    # ── Fujifilm ─────────────────────────────────────────────────────────────
    {"title": "Fujifilm GW690III",         "make": "Fujifilm", "year": "1992-2002", "type": "Rangefinder", "format": "120 Film", "mount": "Fixed (EBC 90mm f/3.5)", "category": "Camera", "notes": "6x9 'Texas Leica' medium format rangefinder."},
    {"title": "Fujifilm GA645",            "make": "Fujifilm", "year": "1995-2002", "type": "Rangefinder", "format": "120 Film", "mount": "Fixed (60mm f/4)", "category": "Camera", "notes": "Autofocus 645 compact."},
    {"title": "Fujifilm Klasse S / W",     "make": "Fujifilm", "year": "2007-2014", "type": "Point & Shoot", "format": "35mm Film", "mount": "Fixed (38mm/28mm)", "category": "Camera", "notes": "Late premium film compacts."},
    {"title": "Fujifilm Natura S",         "make": "Fujifilm", "year": "2004-2012", "type": "Point & Shoot", "format": "35mm Film", "mount": "Fixed (24mm f/1.9)", "category": "Camera", "notes": "Japan-only low-light compact; cult item."},
    {"title": "Fujifilm S2 Pro / S5 Pro",  "make": "Fujifilm", "year": "2002-2009", "type": "DSLR", "format": "APS-C", "mount": "Nikon F", "category": "Camera", "notes": "Super CCD DSLRs in Nikon bodies; famous skin tones."},
    {"title": "Fujifilm X100 (original)",  "make": "Fujifilm", "year": "2011-2013", "type": "Mirrorless", "format": "APS-C", "mount": "Fixed (23mm f/2)", "category": "Camera", "notes": "Hybrid OVF/EVF; launched the X system and the retro wave."},
    {"title": "Fujifilm X100V / X100VI",   "make": "Fujifilm", "year": "2020-present", "type": "Mirrorless", "format": "APS-C", "mount": "Fixed (23mm f/2)", "category": "Camera", "notes": "Viral sensation; VI adds IBIS and 40MP."},
    {"title": "Fujifilm X-Pro1",           "make": "Fujifilm", "year": "2012-2016", "type": "Mirrorless", "format": "APS-C", "mount": "Fujifilm X", "category": "Camera", "notes": "First interchangeable X body."},
    {"title": "Fujifilm X-Pro3",           "make": "Fujifilm", "year": "2019-2023", "type": "Mirrorless", "format": "APS-C", "mount": "Fujifilm X", "category": "Camera", "notes": "Hidden LCD; film-era handling statement."},
    {"title": "Fujifilm X-T1",             "make": "Fujifilm", "year": "2014-2016", "type": "Mirrorless", "format": "APS-C", "mount": "Fujifilm X", "category": "Camera", "notes": "Dial-driven SLR-style X."},
    {"title": "Fujifilm X-T3 / X-T4",      "make": "Fujifilm", "year": "2018-2022", "type": "Mirrorless", "format": "APS-C", "mount": "Fujifilm X", "category": "Camera", "notes": "26MP X-Trans 4 generation."},
    {"title": "Fujifilm X-T5",             "make": "Fujifilm", "year": "2022-present", "type": "Mirrorless", "format": "APS-C", "mount": "Fujifilm X", "category": "Camera", "notes": "40MP, classic dials."},
    {"title": "Fujifilm X-E4",             "make": "Fujifilm", "year": "2021-2023", "type": "Mirrorless", "format": "APS-C", "mount": "Fujifilm X", "category": "Camera", "notes": "Minimalist rangefinder-style X."},
    {"title": "Fujifilm GFX 50S",          "make": "Fujifilm", "year": "2017-2021", "type": "Mirrorless", "format": "Medium Format", "mount": "Fujifilm G", "category": "Camera", "notes": "Brought medium format under $7k."},
    {"title": "Fujifilm GFX 100 / 100S",   "make": "Fujifilm", "year": "2019-present", "type": "Mirrorless", "format": "Medium Format", "mount": "Fujifilm G", "category": "Camera", "notes": "102MP stabilized medium format."},

    # ── Pentax ───────────────────────────────────────────────────────────────
    {"title": "Pentax ME Super",           "make": "Pentax",   "year": "1980-1986", "type": "SLR (film)", "format": "35mm Film", "mount": "Pentax K", "category": "Camera", "notes": "Tiny aperture-priority body with push-button speeds."},
    {"title": "Pentax Super Program (Super A)", "make": "Pentax", "year": "1983-1987", "type": "SLR (film)", "format": "35mm Film", "mount": "Pentax KA", "category": "Camera", "notes": "European Camera of the Year 1983."},
    {"title": "Pentax P30 / P3",           "make": "Pentax",   "year": "1985-1990", "type": "SLR (film)", "format": "35mm Film", "mount": "Pentax KA", "category": "Camera", "notes": "Common student body."},
    {"title": "Pentax Z-1 / PZ-1",         "make": "Pentax",   "year": "1991-1995", "type": "SLR (film)", "format": "35mm Film", "mount": "Pentax KAF2", "category": "Camera", "notes": "Hyper Program AF flagship."},
    {"title": "Pentax MZ-S",               "make": "Pentax",   "year": "2001-2006", "type": "SLR (film)", "format": "35mm Film", "mount": "Pentax KAF2", "category": "Camera", "notes": "Last pro Pentax film body; angled top LCD."},
    {"title": "Pentax 645N",               "make": "Pentax",   "year": "1997-2009", "type": "Medium Format", "format": "120 Film", "mount": "Pentax 645", "category": "Camera", "notes": "Autofocus 645; landscape staple."},
    {"title": "Pentax *ist D",             "make": "Pentax",   "year": "2003-2006", "type": "DSLR", "format": "APS-C", "mount": "Pentax KAF", "category": "Camera", "notes": "First Pentax DSLR."},
    {"title": "Pentax K10D",               "make": "Pentax",   "year": "2006-2008", "type": "DSLR", "format": "APS-C", "mount": "Pentax KAF2", "category": "Camera", "notes": "Weather-sealed 10MP with IBIS."},
    {"title": "Pentax K-5 / K-5 II",       "make": "Pentax",   "year": "2010-2014", "type": "DSLR", "format": "APS-C", "mount": "Pentax KAF2", "category": "Camera", "notes": "Compact rugged enthusiast line peak."},
    {"title": "Pentax K-1 / K-1 II",       "make": "Pentax",   "year": "2016-present", "type": "DSLR", "format": "35mm Full Frame", "mount": "Pentax KAF2", "category": "Camera", "notes": "36MP full frame with pixel-shift; astro tracer."},
    {"title": "Pentax K-3 III",            "make": "Pentax",   "year": "2021-present", "type": "DSLR", "format": "APS-C", "mount": "Pentax KAF2", "category": "Camera", "notes": "The DSLR holdout; superb OVF."},
    {"title": "Pentax 645D / 645Z",        "make": "Pentax",   "year": "2010-2020", "type": "DSLR", "format": "Medium Format", "mount": "Pentax 645AF2", "category": "Camera", "notes": "Affordable digital medium format pioneers."},

    # ── Olympus / OM System ──────────────────────────────────────────────────
    {"title": "Olympus OM-3 / OM-3Ti",     "make": "Olympus",  "year": "1983-2002", "type": "SLR (film)", "format": "35mm Film", "mount": "Olympus OM", "category": "Camera", "notes": "Mechanical with multi-spot meter; OM-3Ti is a top collectible."},
    {"title": "Olympus OM-4 / OM-4Ti",     "make": "Olympus",  "year": "1983-2002", "type": "SLR (film)", "format": "35mm Film", "mount": "Olympus OM", "category": "Camera", "notes": "Multi-spot metering electronic flagship."},
    {"title": "Olympus XA2",               "make": "Olympus",  "year": "1980-1986", "type": "Point & Shoot", "format": "35mm Film", "mount": "Fixed (35mm f/3.5)", "category": "Camera", "notes": "Zone-focus clamshell; street favorite."},
    {"title": "Olympus E-1",               "make": "Olympus",  "year": "2003-2007", "type": "DSLR", "format": "Four Thirds", "mount": "Four Thirds", "category": "Camera", "notes": "First Four Thirds camera; dust-reduction pioneer."},
    {"title": "Olympus PEN E-P1",          "make": "Olympus",  "year": "2009-2011", "type": "Mirrorless", "format": "Micro Four Thirds", "mount": "Micro Four Thirds", "category": "Camera", "notes": "Digital PEN revival; early mirrorless milestone."},
    {"title": "Olympus PEN-F (digital)",   "make": "Olympus",  "year": "2016-2019", "type": "Mirrorless", "format": "Micro Four Thirds", "mount": "Micro Four Thirds", "category": "Camera", "notes": "Gorgeous retro body; mono profiles dial."},
    {"title": "Olympus OM-D E-M5",         "make": "Olympus",  "year": "2012-2015", "type": "Mirrorless", "format": "Micro Four Thirds", "mount": "Micro Four Thirds", "category": "Camera", "notes": "5-axis IBIS breakthrough."},
    {"title": "Olympus OM-D E-M1 II / III","make": "Olympus",  "year": "2016-2023", "type": "Mirrorless", "format": "Micro Four Thirds", "mount": "Micro Four Thirds", "category": "Camera", "notes": "Pro speed M43; 60fps bursts."},
    {"title": "OM System OM-1",            "make": "OM System","year": "2022-present", "type": "Mirrorless", "format": "Micro Four Thirds", "mount": "Micro Four Thirds", "category": "Camera", "notes": "Stacked-sensor flagship bearing the classic name."},

    # ── Panasonic ────────────────────────────────────────────────────────────
    {"title": "Panasonic Lumix G1",        "make": "Panasonic","year": "2008-2010", "type": "Mirrorless", "format": "Micro Four Thirds", "mount": "Micro Four Thirds", "category": "Camera", "notes": "The first mirrorless interchangeable-lens camera, period."},
    {"title": "Panasonic Lumix GH4",       "make": "Panasonic","year": "2014-2017", "type": "Mirrorless", "format": "Micro Four Thirds", "mount": "Micro Four Thirds", "category": "Camera", "notes": "First 4K mirrorless; indie video standard."},
    {"title": "Panasonic Lumix GH5 / GH6", "make": "Panasonic","year": "2017-present", "type": "Mirrorless", "format": "Micro Four Thirds", "mount": "Micro Four Thirds", "category": "Camera", "notes": "Video workhorses; 10-bit internal."},
    {"title": "Panasonic Lumix G9",        "make": "Panasonic","year": "2017-present", "type": "Mirrorless", "format": "Micro Four Thirds", "mount": "Micro Four Thirds", "category": "Camera", "notes": "Stills-focused M43 flagship."},
    {"title": "Panasonic Lumix LX100",     "make": "Panasonic","year": "2014-2019", "type": "Point & Shoot", "format": "Micro Four Thirds", "mount": "Fixed (Leica 24-75mm eq.)", "category": "Camera", "notes": "Multi-aspect M43 compact."},
    {"title": "Panasonic Lumix S1 / S1R",  "make": "Panasonic","year": "2019-2023", "type": "Mirrorless", "format": "35mm Full Frame", "mount": "Leica L", "category": "Camera", "notes": "L-mount alliance full-frame debut."},
    {"title": "Panasonic Lumix S5 / S5 II","make": "Panasonic","year": "2020-present", "type": "Mirrorless", "format": "35mm Full Frame", "mount": "Leica L", "category": "Camera", "notes": "S5 II added phase-detect AF."},

    # ── Leica (1980-present additions) ───────────────────────────────────────
    {"title": "Leica M4-P",                "make": "Leica",    "year": "1980-1987", "type": "Rangefinder", "format": "35mm Film", "mount": "Leica M", "category": "Camera", "notes": "Six framelines; bridge to the M6."},
    {"title": "Leica M7",                  "make": "Leica",    "year": "2002-2018", "type": "Rangefinder", "format": "35mm Film", "mount": "Leica M", "category": "Camera", "notes": "Aperture-priority electronic M."},
    {"title": "Leica M8",                  "make": "Leica",    "year": "2006-2009", "type": "Rangefinder", "format": "APS-H", "mount": "Leica M", "category": "Camera", "notes": "First digital M; IR-sensitive sensor quirk."},
    {"title": "Leica M9",                  "make": "Leica",    "year": "2009-2012", "type": "Rangefinder", "format": "35mm Full Frame", "mount": "Leica M", "category": "Camera", "notes": "First full-frame digital M; CCD rendering cult."},
    {"title": "Leica M10",                 "make": "Leica",    "year": "2017-2022", "type": "Rangefinder", "format": "35mm Full Frame", "mount": "Leica M", "category": "Camera", "notes": "Slimmed to film-M proportions."},
    {"title": "Leica Q / Q2 / Q3",         "make": "Leica",    "year": "2015-present", "type": "Point & Shoot", "format": "35mm Full Frame", "mount": "Fixed (Summilux 28mm f/1.7)", "category": "Camera", "notes": "Full-frame fixed-lens line; enormous success."},
    {"title": "Leica SL2",                 "make": "Leica",    "year": "2019-present", "type": "Mirrorless", "format": "35mm Full Frame", "mount": "Leica L", "category": "Camera", "notes": "47MP L-mount flagship."},
    {"title": "Leica Minilux",             "make": "Leica",    "year": "1995-2003", "type": "Point & Shoot", "format": "35mm Film", "mount": "Fixed (Summarit 40mm f/2.4)", "category": "Camera", "notes": "Titanium premium compact."},
    {"title": "Leica R5 / R6 / R7",        "make": "Leica",    "year": "1986-1997", "type": "SLR (film)", "format": "35mm Film", "mount": "Leica R", "category": "Camera", "notes": "R6/R6.2 are the prized all-mechanical models."},

    # ── Contax / Yashica / Konica / Ricoh ────────────────────────────────────
    {"title": "Contax 139 Quartz",         "make": "Contax",   "year": "1979-1987", "type": "SLR (film)", "format": "35mm Film", "mount": "Contax/Yashica", "category": "Camera", "notes": "Compact entry to Zeiss glass."},
    {"title": "Contax 167MT",              "make": "Contax",   "year": "1986-1992", "type": "SLR (film)", "format": "35mm Film", "mount": "Contax/Yashica", "category": "Camera", "notes": ""},
    {"title": "Contax S2",                 "make": "Contax",   "year": "1992-2000", "type": "SLR (film)", "format": "35mm Film", "mount": "Contax/Yashica", "category": "Camera", "notes": "Mechanical titanium 60th-anniversary body."},
    {"title": "Contax Aria",               "make": "Contax",   "year": "1998-2003", "type": "SLR (film)", "format": "35mm Film", "mount": "Contax/Yashica", "category": "Camera", "notes": "Light, matrix-metered favorite."},
    {"title": "Contax G1",                 "make": "Contax",   "year": "1994-1996", "type": "Rangefinder", "format": "35mm Film", "mount": "Contax G", "category": "Camera", "notes": "AF rangefinder with Zeiss G lenses."},
    {"title": "Contax 645",                "make": "Contax",   "year": "1999-2005", "type": "Medium Format", "format": "120 Film", "mount": "Contax 645", "category": "Camera", "notes": "AF 645 with Zeiss 80/2; wedding legend."},
    {"title": "Yashica T4 / T5",           "make": "Yashica",  "year": "1990-2002", "type": "Point & Shoot", "format": "35mm Film", "mount": "Fixed (Zeiss Tessar 35mm f/3.5)", "category": "Camera", "notes": "Terry Richardson made it famous; prices exploded."},
    {"title": "Konica Hexar AF",           "make": "Konica",   "year": "1993-1999", "type": "Point & Shoot", "format": "35mm Film", "mount": "Fixed (35mm f/2)", "category": "Camera", "notes": "Whisper-quiet 'silent mode'; superb lens."},
    {"title": "Konica Hexar RF",           "make": "Konica",   "year": "1999-2003", "type": "Rangefinder", "format": "35mm Film", "mount": "Leica M", "category": "Camera", "notes": "Motorized M-mount rangefinder."},
    {"title": "Ricoh GR1 / GR1s / GR1v",   "make": "Ricoh",    "year": "1996-2005", "type": "Point & Shoot", "format": "35mm Film", "mount": "Fixed (GR 28mm f/2.8)", "category": "Camera", "notes": "Street-photography icon; superb GR lens."},
    {"title": "Ricoh GR / GR II / GR III / GR IIIx", "make": "Ricoh", "year": "2013-present", "type": "Point & Shoot", "format": "APS-C", "mount": "Fixed (18.3mm/26.1mm)", "category": "Camera", "notes": "Digital GR line; pocket APS-C street standard."},

    # ── Medium format (1980s-2000s) ──────────────────────────────────────────
    {"title": "Hasselblad 501CM",          "make": "Hasselblad","year": "1997-2005", "type": "Medium Format", "format": "120 Film", "mount": "Hasselblad V", "category": "Camera", "notes": "Gliding mirror; popular V-system finale."},
    {"title": "Hasselblad H1 / H2",        "make": "Hasselblad","year": "2002-2008", "type": "Medium Format", "format": "120 Film / Digital back", "mount": "Hasselblad H", "category": "Camera", "notes": "AF 645 system co-built with Fuji."},
    {"title": "Hasselblad X2D 100C",       "make": "Hasselblad","year": "2022-present", "type": "Mirrorless", "format": "Medium Format", "mount": "Hasselblad X", "category": "Camera", "notes": "100MP with IBIS."},
    {"title": "Hasselblad 907X & CFV 100C","make": "Hasselblad","year": "2024-present", "type": "Mirrorless", "format": "Medium Format", "mount": "Hasselblad X / V", "category": "Camera", "notes": "Digital back mates to vintage V bodies."},
    {"title": "Mamiya RB67 Pro-SD",        "make": "Mamiya",   "year": "1990-2010", "type": "Medium Format", "format": "120 Film", "mount": "Mamiya RB", "category": "Camera", "notes": "Mechanical 6x7 studio tank; rotating back."},
    {"title": "Mamiya RZ67 Pro II",        "make": "Mamiya",   "year": "1993-2010", "type": "Medium Format", "format": "120 Film", "mount": "Mamiya RZ", "category": "Camera", "notes": "Electronic 6x7; fashion-studio staple."},
    {"title": "Mamiya 645 Pro TL",         "make": "Mamiya",   "year": "1997-2006", "type": "Medium Format", "format": "120 Film", "mount": "Mamiya 645", "category": "Camera", "notes": "Modular 645 system."},
    {"title": "Mamiya 6",                  "make": "Mamiya",   "year": "1989-1995", "type": "Rangefinder", "format": "120 Film", "mount": "Mamiya 6", "category": "Camera", "notes": "Collapsible 6x6 rangefinder; razor-sharp lenses."},
    {"title": "Mamiya 7 / 7II",            "make": "Mamiya",   "year": "1995-2014", "type": "Rangefinder", "format": "120 Film", "mount": "Mamiya 7", "category": "Camera", "notes": "6x7 rangefinder; arguably the sharpest MF system ever. Prices have soared."},
    {"title": "Bronica SQ-A",              "make": "Bronica",  "year": "1982-2003", "type": "Medium Format", "format": "120 Film", "mount": "Bronica SQ", "category": "Camera", "notes": "6x6 Hasselblad alternative."},
    {"title": "Bronica ETRSi",             "make": "Bronica",  "year": "1988-2004", "type": "Medium Format", "format": "120 Film", "mount": "Bronica ETR", "category": "Camera", "notes": "645 workhorse."},
    {"title": "Bronica GS-1",              "make": "Bronica",  "year": "1983-2002", "type": "Medium Format", "format": "120 Film", "mount": "Bronica GS", "category": "Camera", "notes": "Lightest 6x7 SLR system."},
    {"title": "Rollei 6008 Integral",      "make": "Rolleiflex","year": "1995-2010", "type": "Medium Format", "format": "120 Film", "mount": "Rollei 6000", "category": "Camera", "notes": "Electronic 6x6 with Zeiss/Schneider PQ lenses."},

    # ── Other digital landmarks ──────────────────────────────────────────────
    {"title": "Kodak DCS 100",             "make": "Kodak",    "year": "1991-1994", "type": "DSLR", "format": "APS-C (1.3MP)", "mount": "Nikon F", "category": "Camera", "notes": "First commercial DSLR; Nikon F3 body with tethered storage unit."},
    {"title": "Kodak DCS Pro 14n",         "make": "Kodak",    "year": "2003-2005", "type": "DSLR", "format": "35mm Full Frame", "mount": "Nikon F", "category": "Camera", "notes": "Early 14MP full frame."},
    {"title": "Epson R-D1",                "make": "Epson",    "year": "2004-2007", "type": "Rangefinder", "format": "APS-C", "mount": "Leica M", "category": "Camera", "notes": "First digital rangefinder; wind-lever charged shutter. Cult collectible."},
    {"title": "Sigma DP1 / DP2",           "make": "Sigma",    "year": "2008-2013", "type": "Point & Shoot", "format": "APS-C (Foveon)", "mount": "Fixed", "category": "Camera", "notes": "Foveon X3 compacts; unique color rendering."},
    {"title": "Sigma fp",                  "make": "Sigma",    "year": "2019-present", "type": "Mirrorless", "format": "35mm Full Frame", "mount": "Leica L", "category": "Camera", "notes": "World's smallest full-frame body; modular cine use."},
    {"title": "Samsung NX1",               "make": "Samsung",  "year": "2014-2016", "type": "Mirrorless", "format": "APS-C", "mount": "Samsung NX", "category": "Camera", "notes": "28MP BSI, 4K; Samsung's swan song in cameras."},
    {"title": "Nikon Coolpix 950",         "make": "Nikon",    "year": "1999-2000", "type": "Point & Shoot", "format": "1/2\" CCD", "mount": "Fixed swivel", "category": "Camera", "notes": "Iconic twist-body early digicam."},
    {"title": "Canon PowerShot G7 X Mark II / III", "make": "Canon", "year": "2016-present", "type": "Point & Shoot", "format": "1\"", "mount": "Fixed zoom", "category": "Camera", "notes": "Vlogging-era compact staple."},

    # ── Canon lenses ─────────────────────────────────────────────────────────
    {"title": "Canon nFD 50mm f/1.2 L",    "make": "Canon", "mount": "Canon FD", "focal_length": "50mm", "max_aperture": "f/1.2", "lens_type": "Prime", "year": "1980-1992", "category": "Lens", "notes": "Aspherical FD-era flagship."},
    {"title": "Canon nFD 24mm f/1.4 L",    "make": "Canon", "mount": "Canon FD", "focal_length": "24mm", "max_aperture": "f/1.4", "lens_type": "Wide", "year": "1981-1992", "category": "Lens", "notes": "Rare FD L wide."},
    {"title": "Canon EF 50mm f/1.8 II",    "make": "Canon", "mount": "Canon EF", "focal_length": "50mm", "max_aperture": "f/1.8", "lens_type": "Prime", "year": "1990-2015", "category": "Lens", "notes": "The 'nifty fifty'; tens of millions sold."},
    {"title": "Canon EF 50mm f/1.0 L USM", "make": "Canon", "mount": "Canon EF", "focal_length": "50mm", "max_aperture": "f/1.0", "lens_type": "Prime", "year": "1989-2000", "category": "Lens", "notes": "Fastest AF SLR lens ever sold; major collectible."},
    {"title": "Canon EF 85mm f/1.2L II",   "make": "Canon", "mount": "Canon EF", "focal_length": "85mm", "max_aperture": "f/1.2", "lens_type": "Portrait", "year": "2006-2020", "category": "Lens", "notes": "Portrait benchmark for a generation."},
    {"title": "Canon EF 135mm f/2L",       "make": "Canon", "mount": "Canon EF", "focal_length": "135mm", "max_aperture": "f/2", "lens_type": "Telephoto", "year": "1996-2021", "category": "Lens", "notes": "Beloved compression and bokeh."},
    {"title": "Canon EF 200mm f/1.8L",     "make": "Canon", "mount": "Canon EF", "focal_length": "200mm", "max_aperture": "f/1.8", "lens_type": "Telephoto", "year": "1988-2004", "category": "Lens", "notes": "'Eye of Sauron'; rare and coveted."},
    {"title": "Canon EF 24-70mm f/2.8L II","make": "Canon", "mount": "Canon EF", "focal_length": "24-70mm", "max_aperture": "f/2.8", "lens_type": "Zoom", "year": "2012-present", "category": "Lens", "notes": "Standard pro zoom."},
    {"title": "Canon EF 70-200mm f/2.8L IS II / III", "make": "Canon", "mount": "Canon EF", "focal_length": "70-200mm", "max_aperture": "f/2.8", "lens_type": "Zoom", "year": "2010-present", "category": "Lens", "notes": "Press-room fixture."},
    {"title": "Canon EF 16-35mm f/2.8L III","make": "Canon","mount": "Canon EF", "focal_length": "16-35mm", "max_aperture": "f/2.8", "lens_type": "Ultra-Wide", "year": "2016-present", "category": "Lens", "notes": ""},
    {"title": "Canon EF 100mm f/2.8L Macro IS", "make": "Canon", "mount": "Canon EF", "focal_length": "100mm", "max_aperture": "f/2.8", "lens_type": "Macro", "year": "2009-present", "category": "Lens", "notes": "Hybrid-IS macro standard."},
    {"title": "Canon EF 300mm f/2.8L IS",  "make": "Canon", "mount": "Canon EF", "focal_length": "300mm", "max_aperture": "f/2.8", "lens_type": "Telephoto", "year": "1999-2011", "category": "Lens", "notes": "Sports/wildlife classic."},
    {"title": "Canon RF 50mm f/1.2L",      "make": "Canon", "mount": "Canon RF", "focal_length": "50mm", "max_aperture": "f/1.2", "lens_type": "Prime", "year": "2018-present", "category": "Lens", "notes": "Optically stunning RF statement lens."},
    {"title": "Canon RF 28-70mm f/2L",     "make": "Canon", "mount": "Canon RF", "focal_length": "28-70mm", "max_aperture": "f/2", "lens_type": "Zoom", "year": "2018-present", "category": "Lens", "notes": "Unprecedented f/2 standard zoom."},
    {"title": "Canon RF 85mm f/1.2L",      "make": "Canon", "mount": "Canon RF", "focal_length": "85mm", "max_aperture": "f/1.2", "lens_type": "Portrait", "year": "2019-present", "category": "Lens", "notes": ""},
    {"title": "Canon RF 100-500mm f/4.5-7.1L", "make": "Canon", "mount": "Canon RF", "focal_length": "100-500mm", "max_aperture": "f/4.5-7.1", "lens_type": "Zoom", "year": "2020-present", "category": "Lens", "notes": "Wildlife favorite."},

    # ── Nikon lenses ─────────────────────────────────────────────────────────
    {"title": "Nikkor 50mm f/1.4 AI-s",    "make": "Nikon", "mount": "Nikon F", "focal_length": "50mm", "max_aperture": "f/1.4", "lens_type": "Prime", "year": "1981-2020", "category": "Lens", "notes": "Manual-focus standard; four decades in production."},
    {"title": "Nikkor 105mm f/2.5 AI-s",   "make": "Nikon", "mount": "Nikon F", "focal_length": "105mm", "max_aperture": "f/2.5", "lens_type": "Portrait", "year": "1981-2005", "category": "Lens", "notes": "The 'Afghan Girl' lens."},
    {"title": "Nikkor 180mm f/2.8 ED AI-s","make": "Nikon", "mount": "Nikon F", "focal_length": "180mm", "max_aperture": "f/2.8", "lens_type": "Telephoto", "year": "1981-2005", "category": "Lens", "notes": "Compact tele legend."},
    {"title": "Nikkor AF 85mm f/1.4D",     "make": "Nikon", "mount": "Nikon F", "focal_length": "85mm", "max_aperture": "f/1.4", "lens_type": "Portrait", "year": "1995-2010", "category": "Lens", "notes": "'Cream machine'."},
    {"title": "Nikkor AF DC 105mm & 135mm f/2", "make": "Nikon", "mount": "Nikon F", "focal_length": "105/135mm", "max_aperture": "f/2", "lens_type": "Portrait", "year": "1990-2020", "category": "Lens", "notes": "Defocus-control bokeh tuning; unique to Nikon."},
    {"title": "Nikkor AF 28mm f/1.4D",     "make": "Nikon", "mount": "Nikon F", "focal_length": "28mm", "max_aperture": "f/1.4", "lens_type": "Wide", "year": "1994-2006", "category": "Lens", "notes": "Hand-ground aspheric; collector grail."},
    {"title": "Nikkor AF-S 14-24mm f/2.8G","make": "Nikon", "mount": "Nikon F", "focal_length": "14-24mm", "max_aperture": "f/2.8", "lens_type": "Ultra-Wide", "year": "2007-present", "category": "Lens", "notes": "Redefined wide zooms; adapted to everything."},
    {"title": "Nikkor AF-S 24-70mm f/2.8G / E VR", "make": "Nikon", "mount": "Nikon F", "focal_length": "24-70mm", "max_aperture": "f/2.8", "lens_type": "Zoom", "year": "2007-present", "category": "Lens", "notes": "Pro standard zoom."},
    {"title": "Nikkor AF-S 70-200mm f/2.8E FL VR", "make": "Nikon", "mount": "Nikon F", "focal_length": "70-200mm", "max_aperture": "f/2.8", "lens_type": "Zoom", "year": "2016-present", "category": "Lens", "notes": "Final, sharpest F-mount 70-200."},
    {"title": "Nikkor AF-S 58mm f/1.4G",   "make": "Nikon", "mount": "Nikon F", "focal_length": "58mm", "max_aperture": "f/1.4", "lens_type": "Prime", "year": "2013-present", "category": "Lens", "notes": "Character-first homage to the Noct."},
    {"title": "Nikkor AF-S 105mm f/1.4E",  "make": "Nikon", "mount": "Nikon F", "focal_length": "105mm", "max_aperture": "f/1.4", "lens_type": "Portrait", "year": "2016-present", "category": "Lens", "notes": "First 105/1.4 ever; staggering rendering."},
    {"title": "Nikkor Z 58mm f/0.95 S Noct", "make": "Nikon", "mount": "Nikon Z", "focal_length": "58mm", "max_aperture": "f/0.95", "lens_type": "Prime", "year": "2019-present", "category": "Lens", "notes": "$8k manual-focus halo lens."},
    {"title": "Nikkor Z 50mm f/1.8 S",     "make": "Nikon", "mount": "Nikon Z", "focal_length": "50mm", "max_aperture": "f/1.8", "lens_type": "Prime", "year": "2018-present", "category": "Lens", "notes": "The humble f/1.8 that outresolves old f/1.4s."},
    {"title": "Nikkor Z 70-200mm f/2.8 VR S", "make": "Nikon", "mount": "Nikon Z", "focal_length": "70-200mm", "max_aperture": "f/2.8", "lens_type": "Zoom", "year": "2020-present", "category": "Lens", "notes": ""},

    # ── Sony / Minolta lenses ────────────────────────────────────────────────
    {"title": "Minolta AF 85mm f/1.4 G",   "make": "Minolta", "mount": "Minolta A", "focal_length": "85mm", "max_aperture": "f/1.4", "lens_type": "Portrait", "year": "1987-2006", "category": "Lens", "notes": "G-series portrait gem."},
    {"title": "Minolta AF 135mm f/2.8 STF","make": "Minolta", "mount": "Minolta A", "focal_length": "135mm", "max_aperture": "f/2.8 (T4.5)", "lens_type": "Portrait", "year": "1999-2006", "category": "Lens", "notes": "Apodization element; smoothest bokeh ever made."},
    {"title": "Sony Zeiss 55mm f/1.8 ZA",  "make": "Sony", "mount": "Sony E", "focal_length": "55mm", "max_aperture": "f/1.8", "lens_type": "Prime", "year": "2013-present", "category": "Lens", "notes": "Early FE benchmark prime."},
    {"title": "Sony Zeiss 35mm f/1.4 ZA",  "make": "Sony", "mount": "Sony E", "focal_length": "35mm", "max_aperture": "f/1.4", "lens_type": "Prime", "year": "2015-2021", "category": "Lens", "notes": ""},
    {"title": "Sony FE 24-70mm f/2.8 GM II", "make": "Sony", "mount": "Sony E", "focal_length": "24-70mm", "max_aperture": "f/2.8", "lens_type": "Zoom", "year": "2022-present", "category": "Lens", "notes": "Lightest pro standard zoom."},
    {"title": "Sony FE 70-200mm f/2.8 GM OSS II", "make": "Sony", "mount": "Sony E", "focal_length": "70-200mm", "max_aperture": "f/2.8", "lens_type": "Zoom", "year": "2021-present", "category": "Lens", "notes": ""},
    {"title": "Sony FE 85mm f/1.4 GM",     "make": "Sony", "mount": "Sony E", "focal_length": "85mm", "max_aperture": "f/1.4", "lens_type": "Portrait", "year": "2016-present", "category": "Lens", "notes": ""},
    {"title": "Sony FE 50mm f/1.2 GM",     "make": "Sony", "mount": "Sony E", "focal_length": "50mm", "max_aperture": "f/1.2", "lens_type": "Prime", "year": "2021-present", "category": "Lens", "notes": ""},
    {"title": "Sony FE 135mm f/1.8 GM",    "make": "Sony", "mount": "Sony E", "focal_length": "135mm", "max_aperture": "f/1.8", "lens_type": "Portrait", "year": "2019-present", "category": "Lens", "notes": "Among the sharpest lenses ever tested."},
    {"title": "Sony FE 200-600mm f/5.6-6.3 G", "make": "Sony", "mount": "Sony E", "focal_length": "200-600mm", "max_aperture": "f/5.6-6.3", "lens_type": "Zoom", "year": "2019-present", "category": "Lens", "notes": "Wildlife value king."},

    # ── Fujifilm lenses ──────────────────────────────────────────────────────
    {"title": "Fujinon XF 35mm f/1.4 R",   "make": "Fujifilm", "mount": "Fujifilm X", "focal_length": "35mm", "max_aperture": "f/1.4", "lens_type": "Prime", "year": "2012-present", "category": "Lens", "notes": "The beloved 'magic' X prime."},
    {"title": "Fujinon XF 23mm f/1.4 R",   "make": "Fujifilm", "mount": "Fujifilm X", "focal_length": "23mm", "max_aperture": "f/1.4", "lens_type": "Prime", "year": "2013-present", "category": "Lens", "notes": ""},
    {"title": "Fujinon XF 56mm f/1.2 R",   "make": "Fujifilm", "mount": "Fujifilm X", "focal_length": "56mm", "max_aperture": "f/1.2", "lens_type": "Portrait", "year": "2014-present", "category": "Lens", "notes": "APS-C portrait standard."},
    {"title": "Fujinon XF 16-55mm f/2.8",  "make": "Fujifilm", "mount": "Fujifilm X", "focal_length": "16-55mm", "max_aperture": "f/2.8", "lens_type": "Zoom", "year": "2015-present", "category": "Lens", "notes": ""},
    {"title": "Fujinon XF 90mm f/2",       "make": "Fujifilm", "mount": "Fujifilm X", "focal_length": "90mm", "max_aperture": "f/2", "lens_type": "Portrait", "year": "2015-present", "category": "Lens", "notes": "Quad-linear motor; razor sharp."},
    {"title": "Fujinon GF 110mm f/2",      "make": "Fujifilm", "mount": "Fujifilm G", "focal_length": "110mm", "max_aperture": "f/2", "lens_type": "Portrait", "year": "2017-present", "category": "Lens", "notes": "Medium-format portrait stunner."},

    # ── Leica M lenses (1980-present) ────────────────────────────────────────
    {"title": "Leica Summicron-M 35mm f/2 ASPH", "make": "Leica", "mount": "Leica M", "focal_length": "35mm", "max_aperture": "f/2", "lens_type": "Prime", "year": "1997-present", "category": "Lens", "notes": "Reference compact 35."},
    {"title": "Leica APO-Summicron-M 50mm f/2 ASPH", "make": "Leica", "mount": "Leica M", "focal_length": "50mm", "max_aperture": "f/2", "lens_type": "Prime", "year": "2012-present", "category": "Lens", "notes": "Apochromatic; often called the most perfect 50mm."},
    {"title": "Leica Summilux-M 50mm f/1.4 ASPH", "make": "Leica", "mount": "Leica M", "focal_length": "50mm", "max_aperture": "f/1.4", "lens_type": "Prime", "year": "2004-present", "category": "Lens", "notes": ""},
    {"title": "Leica Elmarit-M 28mm f/2.8 ASPH", "make": "Leica", "mount": "Leica M", "focal_length": "28mm", "max_aperture": "f/2.8", "lens_type": "Wide", "year": "2006-present", "category": "Lens", "notes": "Pancake-small street wide."},
    {"title": "Leica Tri-Elmar-M 16-18-21mm", "make": "Leica", "mount": "Leica M", "focal_length": "16-18-21mm", "max_aperture": "f/4", "lens_type": "Ultra-Wide", "year": "2006-present", "category": "Lens", "notes": "'WATE' — wide-angle Tri-Elmar."},

    # ── Zeiss / Voigtlander / third party ────────────────────────────────────
    {"title": "Zeiss Planar T* 85mm f/1.4 (C/Y)", "make": "Carl Zeiss", "mount": "Contax/Yashica", "focal_length": "85mm", "max_aperture": "f/1.4", "lens_type": "Portrait", "year": "1980-2005", "category": "Lens", "notes": "Legendary C/Y portrait glass; adapted everywhere."},
    {"title": "Zeiss Distagon T* 21mm f/2.8 (C/Y)", "make": "Carl Zeiss", "mount": "Contax/Yashica", "focal_length": "21mm", "max_aperture": "f/2.8", "lens_type": "Ultra-Wide", "year": "1992-2005", "category": "Lens", "notes": "One of the great wides; C/Y prices soared."},
    {"title": "Zeiss Otus 85mm f/1.4",     "make": "Carl Zeiss", "mount": "Nikon F / Canon EF", "focal_length": "85mm", "max_aperture": "f/1.4", "lens_type": "Portrait", "year": "2014-present", "category": "Lens", "notes": "No-compromise manual portrait Otus."},
    {"title": "Zeiss Batis 25mm & 85mm",   "make": "Carl Zeiss", "mount": "Sony E", "focal_length": "25/85mm", "max_aperture": "f/2-1.8", "lens_type": "Prime", "year": "2015-present", "category": "Lens", "notes": "OLED distance display AF Zeiss for E-mount."},
    {"title": "Voigtlander Nokton 40mm f/1.4 Classic", "make": "Voigtlander", "mount": "Leica M", "focal_length": "40mm", "max_aperture": "f/1.4", "lens_type": "Prime", "year": "2004-present", "category": "Lens", "notes": "Compact budget M favorite."},
    {"title": "Voigtlander 15mm f/4.5 Super Wide Heliar", "make": "Voigtlander", "mount": "Leica M / E", "focal_length": "15mm", "max_aperture": "f/4.5", "lens_type": "Ultra-Wide", "year": "1999-present", "category": "Lens", "notes": ""},
    {"title": "Sigma 35mm f/1.4 DG Art",   "make": "Sigma", "mount": "Multiple", "focal_length": "35mm", "max_aperture": "f/1.4", "lens_type": "Prime", "year": "2012-present", "category": "Lens", "notes": "The lens that rebranded Sigma as a premium maker."},
    {"title": "Sigma 18-35mm f/1.8 DC Art","make": "Sigma", "mount": "Multiple (APS-C)", "focal_length": "18-35mm", "max_aperture": "f/1.8", "lens_type": "Zoom", "year": "2013-present", "category": "Lens", "notes": "First f/1.8 zoom; indie-film staple."},
    {"title": "Sigma 105mm f/1.4 DG Art",  "make": "Sigma", "mount": "Multiple", "focal_length": "105mm", "max_aperture": "f/1.4", "lens_type": "Portrait", "year": "2018-present", "category": "Lens", "notes": "'Bokeh master'."},
    {"title": "Tamron SP 90mm f/2.8 Macro","make": "Tamron", "mount": "Multiple", "focal_length": "90mm", "max_aperture": "f/2.8", "lens_type": "Macro", "year": "1979-present", "category": "Lens", "notes": "Decades-spanning macro classic."},
    {"title": "Tamron 28-75mm f/2.8 Di III","make": "Tamron","mount": "Sony E", "focal_length": "28-75mm", "max_aperture": "f/2.8", "lens_type": "Zoom", "year": "2018-present", "category": "Lens", "notes": "Value pro-zoom phenomenon."},
    {"title": "Tamron 150-600mm Di VC",    "make": "Tamron", "mount": "Multiple", "focal_length": "150-600mm", "max_aperture": "f/5-6.3", "lens_type": "Zoom", "year": "2013-present", "category": "Lens", "notes": "Democratized 600mm wildlife reach."},

    # ── Pentax / Olympus / M43 lenses ────────────────────────────────────────
    {"title": "Pentax FA 31mm f/1.8 Limited", "make": "Pentax", "mount": "Pentax K", "focal_length": "31mm", "max_aperture": "f/1.8", "lens_type": "Prime", "year": "2001-present", "category": "Lens", "notes": "The most famous FA Limited."},
    {"title": "Pentax FA 43mm f/1.9 Limited", "make": "Pentax", "mount": "Pentax K", "focal_length": "43mm", "max_aperture": "f/1.9", "lens_type": "Prime", "year": "1997-present", "category": "Lens", "notes": "True-normal focal length pancake."},
    {"title": "Pentax FA 77mm f/1.8 Limited", "make": "Pentax", "mount": "Pentax K", "focal_length": "77mm", "max_aperture": "f/1.8", "lens_type": "Portrait", "year": "1999-present", "category": "Lens", "notes": "Completes the Limited trio."},
    {"title": "Olympus Zuiko 90mm f/2 Macro", "make": "Olympus", "mount": "Olympus OM", "focal_length": "90mm", "max_aperture": "f/2", "lens_type": "Macro", "year": "1986-2002", "category": "Lens", "notes": "OM-system grail macro."},
    {"title": "Olympus M.Zuiko 25mm f/1.2 PRO", "make": "Olympus", "mount": "Micro Four Thirds", "focal_length": "25mm", "max_aperture": "f/1.2", "lens_type": "Prime", "year": "2016-present", "category": "Lens", "notes": ""},
    {"title": "Panasonic Leica 42.5mm f/1.2 Nocticron", "make": "Panasonic", "mount": "Micro Four Thirds", "focal_length": "42.5mm", "max_aperture": "f/1.2", "lens_type": "Portrait", "year": "2014-present", "category": "Lens", "notes": "M43 portrait flagship."},
    {"title": "Olympus M.Zuiko 12-40mm f/2.8 PRO", "make": "Olympus", "mount": "Micro Four Thirds", "focal_length": "12-40mm", "max_aperture": "f/2.8", "lens_type": "Zoom", "year": "2013-present", "category": "Lens", "notes": "M43 standard pro zoom."},

    # ── Medium format lenses ─────────────────────────────────────────────────
    {"title": "Zeiss Planar CF 80mm f/2.8 T*", "make": "Carl Zeiss", "mount": "Hasselblad V", "focal_length": "80mm", "max_aperture": "f/2.8", "lens_type": "Standard", "year": "1982-2002", "category": "Lens", "notes": "The default Hasselblad normal."},
    {"title": "Mamiya 80mm f/1.9 (645)",   "make": "Mamiya", "mount": "Mamiya 645", "focal_length": "80mm", "max_aperture": "f/1.9", "lens_type": "Standard", "year": "1980-2006", "category": "Lens", "notes": "Fastest medium-format production lens."},
    {"title": "Mamiya N 80mm f/4 L (M7)",  "make": "Mamiya", "mount": "Mamiya 7", "focal_length": "80mm", "max_aperture": "f/4", "lens_type": "Standard", "year": "1995-2014", "category": "Lens", "notes": "Possibly the sharpest production lens ever measured."},
    {"title": "Zeiss Planar 80mm f/2 (Contax 645)", "make": "Carl Zeiss", "mount": "Contax 645", "focal_length": "80mm", "max_aperture": "f/2", "lens_type": "Standard", "year": "1999-2005", "category": "Lens", "notes": "The wedding-photographer legend."},
]
