"""Built-in reference catalog of US and Canadian coins.

Each entry represents a coin series or a notable individual issue (key date,
major variety, etc.).  When a user selects an entry from the Coin Catalog
dialog, the matching fields are pre-filled in the detail form.

Field names match the ``coin`` item type defined in ``type_defs.py``.
"""

from __future__ import annotations
from typing import List, Dict, Any


# ── Data ──────────────────────────────────────────────────────────────────────

CATALOG: List[Dict[str, Any]] = [

    # ── US Half Cents ─────────────────────────────────────────────────────────
    {"title": "Liberty Cap Half Cent",         "series": "Half Cent",        "country": "United States", "denomination": "1/2 Cent", "years": "1793-1797", "metal": "Copper",                    "diameter": "22 mm",   "weight": "6.74 g",  "key_dates": ["1793", "1796 No Pole"],                               "notes": "First US half cent type. 1793 is rare; No Pole variety especially scarce."},
    {"title": "Draped Bust Half Cent",         "series": "Half Cent",        "country": "United States", "denomination": "1/2 Cent", "years": "1800-1808", "metal": "Copper",                    "diameter": "23.5 mm", "weight": "5.44 g",  "key_dates": ["1802/0"],                                             "notes": ""},
    {"title": "Classic Head Half Cent",        "series": "Half Cent",        "country": "United States", "denomination": "1/2 Cent", "years": "1809-1836", "metal": "Copper",                    "diameter": "23.5 mm", "weight": "5.44 g",  "key_dates": ["1831", "1836"],                                       "notes": ""},
    {"title": "Braided Hair Half Cent",        "series": "Half Cent",        "country": "United States", "denomination": "1/2 Cent", "years": "1840-1857", "metal": "Copper",                    "diameter": "23 mm",   "weight": "5.44 g",  "key_dates": ["1840", "1852"],                                       "notes": "Last US half cent. Many dates are proofs only."},

    # ── US Large Cents ────────────────────────────────────────────────────────
    {"title": "Flowing Hair Chain Cent",       "series": "Large Cent",       "country": "United States", "denomination": "1 Cent",   "years": "1793",      "metal": "Copper",                    "diameter": "26-28 mm","weight": "13.48 g", "key_dates": ["1793 AMERI.", "1793 Periods"],                        "notes": "First US cent ever struck. Extremely rare."},
    {"title": "Flowing Hair Wreath Cent",      "series": "Large Cent",       "country": "United States", "denomination": "1 Cent",   "years": "1793",      "metal": "Copper",                    "diameter": "26-28 mm","weight": "13.48 g", "key_dates": ["1793 Strawberry Leaf (4 known)"],                     "notes": ""},
    {"title": "Liberty Cap Large Cent",        "series": "Large Cent",       "country": "United States", "denomination": "1 Cent",   "years": "1793-1796", "metal": "Copper",                    "diameter": "28-29 mm","weight": "10.89 g", "key_dates": ["1793", "1794 S-48 (Head of '94)"],                    "notes": ""},
    {"title": "Draped Bust Large Cent",        "series": "Large Cent",       "country": "United States", "denomination": "1 Cent",   "years": "1796-1807", "metal": "Copper",                    "diameter": "29 mm",   "weight": "10.89 g", "key_dates": ["1799", "1804"],                                       "notes": "1799 is the key date; 1804 is very rare."},
    {"title": "Classic Head Large Cent",       "series": "Large Cent",       "country": "United States", "denomination": "1 Cent",   "years": "1808-1814", "metal": "Copper",                    "diameter": "29 mm",   "weight": "10.89 g", "key_dates": ["1809"],                                               "notes": ""},
    {"title": "Coronet Large Cent",            "series": "Large Cent",       "country": "United States", "denomination": "1 Cent",   "years": "1816-1839", "metal": "Copper",                    "diameter": "28.5 mm", "weight": "10.89 g", "key_dates": ["1823", "1839/6"],                                     "notes": ""},
    {"title": "Braided Hair Large Cent",       "series": "Large Cent",       "country": "United States", "denomination": "1 Cent",   "years": "1839-1857", "metal": "Copper",                    "diameter": "27.5 mm", "weight": "10.89 g", "key_dates": ["1857"],                                               "notes": "Last year is common but marks end of large cent era."},

    # ── US Small Cents ────────────────────────────────────────────────────────
    {"title": "Flying Eagle Cent",             "series": "Small Cent",       "country": "United States", "denomination": "1 Cent",   "years": "1856-1858", "metal": "88% Copper, 12% Nickel",    "diameter": "19.05 mm","weight": "4.67 g",  "key_dates": ["1856 (pattern)", "1858 Large Letters", "1858 Small Letters"], "notes": "1856 is a pattern/rarity. Short-lived series replaced by Indian Head."},
    {"title": "Indian Head Cent",              "series": "Small Cent",       "country": "United States", "denomination": "1 Cent",   "years": "1859-1909", "metal": "Copper-Nickel / Bronze",     "diameter": "19.05 mm","weight": "3.11 g",  "key_dates": ["1864 L on Ribbon", "1877", "1908-S", "1909-S"],       "notes": "1877 is the key date. 1864 L variety and 1908-S/1909-S are branch mint scarce."},
    {"title": "Lincoln Wheat Cent",            "series": "Small Cent",       "country": "United States", "denomination": "1 Cent",   "years": "1909-1958", "metal": "Bronze (95% Cu) / Steel (1943)", "diameter": "19.05 mm","weight": "3.11 g","key_dates": ["1909-S VDB", "1909-S", "1914-D", "1922 Plain", "1931-S", "1943 Copper", "1944 Steel"], "notes": "1909-S VDB is the most famous US coin. 1943 steel cents are common; 1943 copper are extremely rare errors."},
    {"title": "Lincoln Memorial Cent",         "series": "Small Cent",       "country": "United States", "denomination": "1 Cent",   "years": "1959-2008", "metal": "Bronze / Zinc (1982-)",      "diameter": "19.05 mm","weight": "3.11 g",  "key_dates": ["1960 Small Date", "1970-S Small Date", "1972 DDO", "1983 DDR", "1992 Close AM", "1995 DDO"], "notes": "Large cent composition changed to zinc core in 1982. Look for doubled die varieties."},
    {"title": "Lincoln Bicentennial Cent - Birth & Early Childhood", "series": "Small Cent", "country": "United States", "denomination": "1 Cent", "years": "2009", "metal": "Copper-Plated Zinc", "diameter": "19.05 mm", "weight": "2.5 g", "key_dates": [], "notes": "One of four 2009 bicentennial designs. Log cabin reverse."},
    {"title": "Lincoln Bicentennial Cent - Formative Years", "series": "Small Cent", "country": "United States", "denomination": "1 Cent", "years": "2009", "metal": "Copper-Plated Zinc", "diameter": "19.05 mm", "weight": "2.5 g", "key_dates": [], "notes": "Lincoln reading on a log."},
    {"title": "Lincoln Bicentennial Cent - Professional Life", "series": "Small Cent", "country": "United States", "denomination": "1 Cent", "years": "2009", "metal": "Copper-Plated Zinc", "diameter": "19.05 mm", "weight": "2.5 g", "key_dates": [], "notes": "Lincoln in front of Illinois State Capitol."},
    {"title": "Lincoln Bicentennial Cent - Presidency", "series": "Small Cent", "country": "United States", "denomination": "1 Cent", "years": "2009", "metal": "Copper-Plated Zinc", "diameter": "19.05 mm", "weight": "2.5 g", "key_dates": [], "notes": "Unfinished US Capitol dome reverse."},
    {"title": "Lincoln Shield Cent",           "series": "Small Cent",       "country": "United States", "denomination": "1 Cent",   "years": "2010-present", "metal": "Copper-Plated Zinc",    "diameter": "19.05 mm","weight": "2.5 g",   "key_dates": ["2010 Satin Finish", "2019-W (first W mint cent)"],    "notes": "Union Shield reverse. 2019-W is extremely popular with collectors."},

    # ── US Two Cents ──────────────────────────────────────────────────────────
    {"title": "Shield Two Cent Piece",         "series": "Two Cents",        "country": "United States", "denomination": "2 Cents",  "years": "1864-1873", "metal": "Bronze (95% Cu)",            "diameter": "23 mm",   "weight": "6.22 g",  "key_dates": ["1864 Small Motto", "1872", "1873 (proof only)"],       "notes": "First US coin to bear 'In God We Trust'. Short series; 1872 is the key."},

    # ── US Three Cents ────────────────────────────────────────────────────────
    {"title": "Three Cent Silver - Type I",    "series": "Three Cents",      "country": "United States", "denomination": "3 Cents",  "years": "1851-1853", "metal": "75% Silver, 25% Copper",    "diameter": "14 mm",   "weight": "0.80 g",  "key_dates": ["1851-O"],                                             "notes": "Smallest US silver coin. One-year New Orleans mint issue."},
    {"title": "Three Cent Silver - Type II",   "series": "Three Cents",      "country": "United States", "denomination": "3 Cents",  "years": "1854-1858", "metal": "90% Silver",                "diameter": "14 mm",   "weight": "0.75 g",  "key_dates": ["1855"],                                               "notes": ""},
    {"title": "Three Cent Silver - Type III",  "series": "Three Cents",      "country": "United States", "denomination": "3 Cents",  "years": "1859-1873", "metal": "90% Silver",                "diameter": "14 mm",   "weight": "0.75 g",  "key_dates": ["1863", "1873 (proof only)"],                          "notes": ""},
    {"title": "Three Cent Nickel",             "series": "Three Cents",      "country": "United States", "denomination": "3 Cents",  "years": "1865-1889", "metal": "75% Copper, 25% Nickel",    "diameter": "17.9 mm", "weight": "1.94 g",  "key_dates": ["1877", "1878", "1886", "1887/6"],                      "notes": ""},

    # ── US Half Dimes ─────────────────────────────────────────────────────────
    {"title": "Flowing Hair Half Dime",        "series": "Half Dime",        "country": "United States", "denomination": "5 Cents",  "years": "1794-1795", "metal": "89.24% Silver",             "diameter": "16.5 mm", "weight": "1.35 g",  "key_dates": ["1794", "1795"],                                       "notes": "First US half dime."},
    {"title": "Draped Bust Half Dime",         "series": "Half Dime",        "country": "United States", "denomination": "5 Cents",  "years": "1796-1805", "metal": "89.24% Silver",             "diameter": "16.5 mm", "weight": "1.35 g",  "key_dates": ["1796/5 Overdate", "1802"],                            "notes": "1802 is the rarest Draped Bust half dime."},
    {"title": "Capped Bust Half Dime",         "series": "Half Dime",        "country": "United States", "denomination": "5 Cents",  "years": "1829-1837", "metal": "89.24% Silver",             "diameter": "15.5 mm", "weight": "1.35 g",  "key_dates": [],                                                     "notes": ""},
    {"title": "Seated Liberty Half Dime",      "series": "Half Dime",        "country": "United States", "denomination": "5 Cents",  "years": "1837-1873", "metal": "90% Silver",                "diameter": "15.5 mm", "weight": "1.24 g",  "key_dates": ["1846", "1870-S (unknown surviving)"],                 "notes": ""},

    # ── US Nickels ────────────────────────────────────────────────────────────
    {"title": "Shield Nickel",                 "series": "Nickel",           "country": "United States", "denomination": "5 Cents",  "years": "1866-1883", "metal": "75% Copper, 25% Nickel",    "diameter": "20.5 mm", "weight": "5 g",     "key_dates": ["1867 Rays", "1879", "1880", "1881"],                  "notes": "First five-cent nickel. 1879-1881 are rare."},
    {"title": "Liberty / V Nickel",            "series": "Nickel",           "country": "United States", "denomination": "5 Cents",  "years": "1883-1912", "metal": "75% Copper, 25% Nickel",    "diameter": "21.2 mm", "weight": "5 g",     "key_dates": ["1883 No CENTS", "1885", "1886", "1912-S", "1913 (5 known)"], "notes": "1883 No Cents were gold-plated and passed as $5 coins. 1913 is one of the most famous US rarities."},
    {"title": "Buffalo / Indian Head Nickel",  "series": "Nickel",           "country": "United States", "denomination": "5 Cents",  "years": "1913-1938", "metal": "75% Copper, 25% Nickel",    "diameter": "21.2 mm", "weight": "5 g",     "key_dates": ["1913-D Type II", "1913-S Type II", "1916 DDO", "1918/7-D", "1921-S", "1926-S", "1937-D 3-Legged"], "notes": "Designed by James Earle Fraser. The 3-Legged Buffalo (1937-D) is the most popular variety."},
    {"title": "Jefferson Nickel",              "series": "Nickel",           "country": "United States", "denomination": "5 Cents",  "years": "1938-2003", "metal": "75% Copper, 25% Nickel",    "diameter": "21.2 mm", "weight": "5 g",     "key_dates": ["1939 DDR", "1942-D", "1950-D", "1954-S", "1955-D"],  "notes": "Wartime 1942-1945 nickels contain 35% silver. 1950-D has very low mintage."},
    {"title": "Jefferson Nickel - Westward Journey Peace Medal", "series": "Nickel", "country": "United States", "denomination": "5 Cents", "years": "2004", "metal": "75% Copper, 25% Nickel", "diameter": "21.2 mm", "weight": "5 g", "key_dates": [], "notes": "Lewis & Clark peace medal design. First nickel reverse change since 1938."},
    {"title": "Jefferson Nickel - Westward Journey Keelboat", "series": "Nickel", "country": "United States", "denomination": "5 Cents", "years": "2004", "metal": "75% Copper, 25% Nickel", "diameter": "21.2 mm", "weight": "5 g", "key_dates": [], "notes": ""},
    {"title": "Jefferson Nickel - Westward Journey American Bison", "series": "Nickel", "country": "United States", "denomination": "5 Cents", "years": "2005", "metal": "75% Copper, 25% Nickel", "diameter": "21.2 mm", "weight": "5 g", "key_dates": [], "notes": ""},
    {"title": "Jefferson Nickel - Westward Journey Ocean in View", "series": "Nickel", "country": "United States", "denomination": "5 Cents", "years": "2005", "metal": "75% Copper, 25% Nickel", "diameter": "21.2 mm", "weight": "5 g", "key_dates": [], "notes": ""},
    {"title": "Jefferson Nickel - Return to Monticello", "series": "Nickel", "country": "United States", "denomination": "5 Cents", "years": "2006-present", "metal": "75% Copper, 25% Nickel", "diameter": "21.2 mm", "weight": "5 g", "key_dates": ["2019-W", "2020-W", "2021-S Reverse Proof"], "notes": "Forward-facing Jefferson portrait introduced 2006."},

    # ── US Dimes ──────────────────────────────────────────────────────────────
    {"title": "Draped Bust Dime",              "series": "Dime",             "country": "United States", "denomination": "10 Cents", "years": "1796-1807", "metal": "89.24% Silver",             "diameter": "19 mm",   "weight": "2.70 g",  "key_dates": ["1797 16 Stars", "1798/7 Overdate", "1804"],           "notes": "1804 is extremely rare; most known examples are proofs."},
    {"title": "Capped Bust Dime",              "series": "Dime",             "country": "United States", "denomination": "10 Cents", "years": "1809-1837", "metal": "89.24% Silver",             "diameter": "18.8 mm", "weight": "2.70 g",  "key_dates": ["1822", "1827"],                                       "notes": ""},
    {"title": "Seated Liberty Dime",           "series": "Dime",             "country": "United States", "denomination": "10 Cents", "years": "1837-1891", "metal": "90% Silver",                "diameter": "17.9 mm", "weight": "2.49 g",  "key_dates": ["1838-O Small 8", "1844", "1846", "1860-O", "1873-CC No Arrows (1 known)"], "notes": "Long series with many varieties. 1873-CC no arrows is unique."},
    {"title": "Barber Dime",                   "series": "Dime",             "country": "United States", "denomination": "10 Cents", "years": "1892-1916", "metal": "90% Silver",                "diameter": "17.9 mm", "weight": "2.50 g",  "key_dates": ["1894-S (24 known)", "1895-O", "1896-O", "1896-S"],   "notes": "1894-S is one of the most coveted rarities in US coinage."},
    {"title": "Mercury Dime",                  "series": "Dime",             "country": "United States", "denomination": "10 Cents", "years": "1916-1945", "metal": "90% Silver",                "diameter": "17.9 mm", "weight": "2.50 g",  "key_dates": ["1916-D", "1921", "1921-D", "1942/41", "1942/41-D"],  "notes": "1916-D has mintage of 264,000 — the key date. Full Bands designation adds premium."},
    {"title": "Roosevelt Dime",                "series": "Dime",             "country": "United States", "denomination": "10 Cents", "years": "1946-present", "metal": "90% Silver (1946-1964) / Clad (1965-)", "diameter": "17.9 mm", "weight": "2.50 g (Ag) / 2.27 g (clad)", "key_dates": ["1949-S", "1950-S", "1951-S", "1955", "1975 No-S Proof (2 known)", "1982 No-P"], "notes": "Clad composition began 1965. Full Bands designation used for grading. 1982 No-P is a major error coin."},

    # ── US Twenty Cents ───────────────────────────────────────────────────────
    {"title": "Seated Liberty Twenty Cent Piece", "series": "Twenty Cents", "country": "United States", "denomination": "20 Cents", "years": "1875-1878", "metal": "90% Silver",               "diameter": "22 mm",   "weight": "5 g",     "key_dates": ["1876-CC (10 known)", "1877 (proof only)", "1878 (proof only)"], "notes": "Short-lived denomination, confused with quarter. 1876-CC is extremely rare."},

    # ── US Quarters ───────────────────────────────────────────────────────────
    {"title": "Draped Bust Quarter",           "series": "Quarter",          "country": "United States", "denomination": "25 Cents", "years": "1796-1807", "metal": "89.24% Silver",             "diameter": "27.5 mm", "weight": "6.74 g",  "key_dates": ["1796 (6,146 minted)", "1804", "1805"],                "notes": "1796 is the rarest Draped Bust quarter; only 6,146 struck."},
    {"title": "Capped Bust Quarter",           "series": "Quarter",          "country": "United States", "denomination": "25 Cents", "years": "1815-1838", "metal": "89.24% Silver",             "diameter": "26.5 mm", "weight": "6.74 g",  "key_dates": ["1823/2", "1827 (orig. vs. restrike)"],                "notes": ""},
    {"title": "Seated Liberty Quarter",        "series": "Quarter",          "country": "United States", "denomination": "25 Cents", "years": "1838-1891", "metal": "90% Silver",                "diameter": "24.3 mm", "weight": "6.22 g",  "key_dates": ["1842-O Small Date", "1852", "1866-S No Motto", "1873-CC No Arrows"], "notes": "Many varieties. No Motto and arrows varieties add complexity."},
    {"title": "Barber Quarter",                "series": "Quarter",          "country": "United States", "denomination": "25 Cents", "years": "1892-1916", "metal": "90% Silver",                "diameter": "24.3 mm", "weight": "6.25 g",  "key_dates": ["1896-S", "1901-S", "1913-S"],                         "notes": "1901-S (72,664 minted) is the key date."},
    {"title": "Standing Liberty Quarter - Type I", "series": "Quarter",      "country": "United States", "denomination": "25 Cents", "years": "1916-1917", "metal": "90% Silver",                "diameter": "24.3 mm", "weight": "6.25 g",  "key_dates": ["1916 (52,000 minted)"],                               "notes": "Exposed breast on obverse. Very short production, 1916 is extremely rare."},
    {"title": "Standing Liberty Quarter - Type II", "series": "Quarter",     "country": "United States", "denomination": "25 Cents", "years": "1917-1930", "metal": "90% Silver",                "diameter": "24.3 mm", "weight": "6.25 g",  "key_dates": ["1918/7-S Overdate", "1921", "1923-S", "1927-S"],      "notes": "Chainmail covers breast. Full Head (FH) designation used in grading."},
    {"title": "Washington Quarter - Silver",   "series": "Quarter",          "country": "United States", "denomination": "25 Cents", "years": "1932-1964", "metal": "90% Silver",                "diameter": "24.3 mm", "weight": "6.25 g",  "key_dates": ["1932-D", "1932-S", "1936-D"],                         "notes": "1932-D and 1932-S are the key dates. Series ended when silver was removed in 1965."},
    {"title": "Washington Quarter - Clad",     "series": "Quarter",          "country": "United States", "denomination": "25 Cents", "years": "1965-1998", "metal": "Clad (Cu-Ni)",              "diameter": "24.3 mm", "weight": "5.67 g",  "key_dates": ["1982-P No Mintmark", "1983-P", "1983-D"],             "notes": "Clad composition. 1982/1983 had key errors."},

    # ── State Quarters (1999-2008) ────────────────────────────────────────────
    {"title": "Delaware State Quarter",        "series": "State Quarter",    "country": "United States", "denomination": "25 Cents", "years": "1999", "metal": "Clad (Cu-Ni)", "diameter": "24.3 mm", "weight": "5.67 g", "key_dates": [], "notes": "First state quarter. Caesar Rodney on horseback."},
    {"title": "Pennsylvania State Quarter",    "series": "State Quarter",    "country": "United States", "denomination": "25 Cents", "years": "1999", "metal": "Clad (Cu-Ni)", "diameter": "24.3 mm", "weight": "5.67 g", "key_dates": [], "notes": ""},
    {"title": "New Jersey State Quarter",      "series": "State Quarter",    "country": "United States", "denomination": "25 Cents", "years": "1999", "metal": "Clad (Cu-Ni)", "diameter": "24.3 mm", "weight": "5.67 g", "key_dates": [], "notes": "Washington Crossing the Delaware."},
    {"title": "Georgia State Quarter",         "series": "State Quarter",    "country": "United States", "denomination": "25 Cents", "years": "1999", "metal": "Clad (Cu-Ni)", "diameter": "24.3 mm", "weight": "5.67 g", "key_dates": [], "notes": ""},
    {"title": "Connecticut State Quarter",     "series": "State Quarter",    "country": "United States", "denomination": "25 Cents", "years": "1999", "metal": "Clad (Cu-Ni)", "diameter": "24.3 mm", "weight": "5.67 g", "key_dates": [], "notes": ""},
    {"title": "Massachusetts State Quarter",   "series": "State Quarter",    "country": "United States", "denomination": "25 Cents", "years": "2000", "metal": "Clad (Cu-Ni)", "diameter": "24.3 mm", "weight": "5.67 g", "key_dates": [], "notes": ""},
    {"title": "Maryland State Quarter",        "series": "State Quarter",    "country": "United States", "denomination": "25 Cents", "years": "2000", "metal": "Clad (Cu-Ni)", "diameter": "24.3 mm", "weight": "5.67 g", "key_dates": [], "notes": ""},
    {"title": "South Carolina State Quarter",  "series": "State Quarter",    "country": "United States", "denomination": "25 Cents", "years": "2000", "metal": "Clad (Cu-Ni)", "diameter": "24.3 mm", "weight": "5.67 g", "key_dates": [], "notes": ""},
    {"title": "New Hampshire State Quarter",   "series": "State Quarter",    "country": "United States", "denomination": "25 Cents", "years": "2000", "metal": "Clad (Cu-Ni)", "diameter": "24.3 mm", "weight": "5.67 g", "key_dates": [], "notes": "Old Man of the Mountain."},
    {"title": "Virginia State Quarter",        "series": "State Quarter",    "country": "United States", "denomination": "25 Cents", "years": "2000", "metal": "Clad (Cu-Ni)", "diameter": "24.3 mm", "weight": "5.67 g", "key_dates": [], "notes": ""},
    {"title": "New York State Quarter",        "series": "State Quarter",    "country": "United States", "denomination": "25 Cents", "years": "2001", "metal": "Clad (Cu-Ni)", "diameter": "24.3 mm", "weight": "5.67 g", "key_dates": [], "notes": ""},
    {"title": "North Carolina State Quarter",  "series": "State Quarter",    "country": "United States", "denomination": "25 Cents", "years": "2001", "metal": "Clad (Cu-Ni)", "diameter": "24.3 mm", "weight": "5.67 g", "key_dates": [], "notes": "Wright Brothers first flight."},
    {"title": "Rhode Island State Quarter",    "series": "State Quarter",    "country": "United States", "denomination": "25 Cents", "years": "2001", "metal": "Clad (Cu-Ni)", "diameter": "24.3 mm", "weight": "5.67 g", "key_dates": [], "notes": ""},
    {"title": "Vermont State Quarter",         "series": "State Quarter",    "country": "United States", "denomination": "25 Cents", "years": "2001", "metal": "Clad (Cu-Ni)", "diameter": "24.3 mm", "weight": "5.67 g", "key_dates": [], "notes": ""},
    {"title": "Kentucky State Quarter",        "series": "State Quarter",    "country": "United States", "denomination": "25 Cents", "years": "2001", "metal": "Clad (Cu-Ni)", "diameter": "24.3 mm", "weight": "5.67 g", "key_dates": [], "notes": ""},
    {"title": "Tennessee State Quarter",       "series": "State Quarter",    "country": "United States", "denomination": "25 Cents", "years": "2002", "metal": "Clad (Cu-Ni)", "diameter": "24.3 mm", "weight": "5.67 g", "key_dates": [], "notes": ""},
    {"title": "Ohio State Quarter",            "series": "State Quarter",    "country": "United States", "denomination": "25 Cents", "years": "2002", "metal": "Clad (Cu-Ni)", "diameter": "24.3 mm", "weight": "5.67 g", "key_dates": [], "notes": "Astronaut and Wright Flyer."},
    {"title": "Louisiana State Quarter",       "series": "State Quarter",    "country": "United States", "denomination": "25 Cents", "years": "2002", "metal": "Clad (Cu-Ni)", "diameter": "24.3 mm", "weight": "5.67 g", "key_dates": [], "notes": ""},
    {"title": "Indiana State Quarter",         "series": "State Quarter",    "country": "United States", "denomination": "25 Cents", "years": "2002", "metal": "Clad (Cu-Ni)", "diameter": "24.3 mm", "weight": "5.67 g", "key_dates": [], "notes": ""},
    {"title": "Mississippi State Quarter",     "series": "State Quarter",    "country": "United States", "denomination": "25 Cents", "years": "2002", "metal": "Clad (Cu-Ni)", "diameter": "24.3 mm", "weight": "5.67 g", "key_dates": [], "notes": ""},
    {"title": "Illinois State Quarter",        "series": "State Quarter",    "country": "United States", "denomination": "25 Cents", "years": "2003", "metal": "Clad (Cu-Ni)", "diameter": "24.3 mm", "weight": "5.67 g", "key_dates": [], "notes": ""},
    {"title": "Alabama State Quarter",         "series": "State Quarter",    "country": "United States", "denomination": "25 Cents", "years": "2003", "metal": "Clad (Cu-Ni)", "diameter": "24.3 mm", "weight": "5.67 g", "key_dates": [], "notes": ""},
    {"title": "Maine State Quarter",           "series": "State Quarter",    "country": "United States", "denomination": "25 Cents", "years": "2003", "metal": "Clad (Cu-Ni)", "diameter": "24.3 mm", "weight": "5.67 g", "key_dates": [], "notes": ""},
    {"title": "Missouri State Quarter",        "series": "State Quarter",    "country": "United States", "denomination": "25 Cents", "years": "2003", "metal": "Clad (Cu-Ni)", "diameter": "24.3 mm", "weight": "5.67 g", "key_dates": [], "notes": ""},
    {"title": "Arkansas State Quarter",        "series": "State Quarter",    "country": "United States", "denomination": "25 Cents", "years": "2003", "metal": "Clad (Cu-Ni)", "diameter": "24.3 mm", "weight": "5.67 g", "key_dates": [], "notes": ""},
    {"title": "Michigan State Quarter",        "series": "State Quarter",    "country": "United States", "denomination": "25 Cents", "years": "2004", "metal": "Clad (Cu-Ni)", "diameter": "24.3 mm", "weight": "5.67 g", "key_dates": [], "notes": ""},
    {"title": "Florida State Quarter",         "series": "State Quarter",    "country": "United States", "denomination": "25 Cents", "years": "2004", "metal": "Clad (Cu-Ni)", "diameter": "24.3 mm", "weight": "5.67 g", "key_dates": [], "notes": ""},
    {"title": "Texas State Quarter",           "series": "State Quarter",    "country": "United States", "denomination": "25 Cents", "years": "2004", "metal": "Clad (Cu-Ni)", "diameter": "24.3 mm", "weight": "5.67 g", "key_dates": [], "notes": ""},
    {"title": "Iowa State Quarter",            "series": "State Quarter",    "country": "United States", "denomination": "25 Cents", "years": "2004", "metal": "Clad (Cu-Ni)", "diameter": "24.3 mm", "weight": "5.67 g", "key_dates": [], "notes": ""},
    {"title": "Wisconsin State Quarter",       "series": "State Quarter",    "country": "United States", "denomination": "25 Cents", "years": "2004", "metal": "Clad (Cu-Ni)", "diameter": "24.3 mm", "weight": "5.67 g", "key_dates": ["Extra Leaf High", "Extra Leaf Low"], "notes": "Extra Leaf error varieties are popular collectibles."},
    {"title": "California State Quarter",      "series": "State Quarter",    "country": "United States", "denomination": "25 Cents", "years": "2005", "metal": "Clad (Cu-Ni)", "diameter": "24.3 mm", "weight": "5.67 g", "key_dates": [], "notes": ""},
    {"title": "Minnesota State Quarter",       "series": "State Quarter",    "country": "United States", "denomination": "25 Cents", "years": "2005", "metal": "Clad (Cu-Ni)", "diameter": "24.3 mm", "weight": "5.67 g", "key_dates": ["Extra Tree variety"], "notes": "Extra Tree error varieties exist."},
    {"title": "Oregon State Quarter",          "series": "State Quarter",    "country": "United States", "denomination": "25 Cents", "years": "2005", "metal": "Clad (Cu-Ni)", "diameter": "24.3 mm", "weight": "5.67 g", "key_dates": [], "notes": ""},
    {"title": "Kansas State Quarter",          "series": "State Quarter",    "country": "United States", "denomination": "25 Cents", "years": "2005", "metal": "Clad (Cu-Ni)", "diameter": "24.3 mm", "weight": "5.67 g", "key_dates": [], "notes": ""},
    {"title": "West Virginia State Quarter",   "series": "State Quarter",    "country": "United States", "denomination": "25 Cents", "years": "2005", "metal": "Clad (Cu-Ni)", "diameter": "24.3 mm", "weight": "5.67 g", "key_dates": [], "notes": ""},
    {"title": "Nevada State Quarter",          "series": "State Quarter",    "country": "United States", "denomination": "25 Cents", "years": "2006", "metal": "Clad (Cu-Ni)", "diameter": "24.3 mm", "weight": "5.67 g", "key_dates": [], "notes": ""},
    {"title": "Nebraska State Quarter",        "series": "State Quarter",    "country": "United States", "denomination": "25 Cents", "years": "2006", "metal": "Clad (Cu-Ni)", "diameter": "24.3 mm", "weight": "5.67 g", "key_dates": [], "notes": ""},
    {"title": "Colorado State Quarter",        "series": "State Quarter",    "country": "United States", "denomination": "25 Cents", "years": "2006", "metal": "Clad (Cu-Ni)", "diameter": "24.3 mm", "weight": "5.67 g", "key_dates": [], "notes": ""},
    {"title": "North Dakota State Quarter",    "series": "State Quarter",    "country": "United States", "denomination": "25 Cents", "years": "2006", "metal": "Clad (Cu-Ni)", "diameter": "24.3 mm", "weight": "5.67 g", "key_dates": [], "notes": ""},
    {"title": "South Dakota State Quarter",    "series": "State Quarter",    "country": "United States", "denomination": "25 Cents", "years": "2006", "metal": "Clad (Cu-Ni)", "diameter": "24.3 mm", "weight": "5.67 g", "key_dates": [], "notes": ""},
    {"title": "Montana State Quarter",         "series": "State Quarter",    "country": "United States", "denomination": "25 Cents", "years": "2007", "metal": "Clad (Cu-Ni)", "diameter": "24.3 mm", "weight": "5.67 g", "key_dates": [], "notes": ""},
    {"title": "Washington State Quarter",      "series": "State Quarter",    "country": "United States", "denomination": "25 Cents", "years": "2007", "metal": "Clad (Cu-Ni)", "diameter": "24.3 mm", "weight": "5.67 g", "key_dates": [], "notes": ""},
    {"title": "Idaho State Quarter",           "series": "State Quarter",    "country": "United States", "denomination": "25 Cents", "years": "2007", "metal": "Clad (Cu-Ni)", "diameter": "24.3 mm", "weight": "5.67 g", "key_dates": [], "notes": ""},
    {"title": "Wyoming State Quarter",         "series": "State Quarter",    "country": "United States", "denomination": "25 Cents", "years": "2007", "metal": "Clad (Cu-Ni)", "diameter": "24.3 mm", "weight": "5.67 g", "key_dates": [], "notes": ""},
    {"title": "Utah State Quarter",            "series": "State Quarter",    "country": "United States", "denomination": "25 Cents", "years": "2007", "metal": "Clad (Cu-Ni)", "diameter": "24.3 mm", "weight": "5.67 g", "key_dates": [], "notes": ""},
    {"title": "Oklahoma State Quarter",        "series": "State Quarter",    "country": "United States", "denomination": "25 Cents", "years": "2008", "metal": "Clad (Cu-Ni)", "diameter": "24.3 mm", "weight": "5.67 g", "key_dates": [], "notes": ""},
    {"title": "New Mexico State Quarter",      "series": "State Quarter",    "country": "United States", "denomination": "25 Cents", "years": "2008", "metal": "Clad (Cu-Ni)", "diameter": "24.3 mm", "weight": "5.67 g", "key_dates": [], "notes": ""},
    {"title": "Arizona State Quarter",         "series": "State Quarter",    "country": "United States", "denomination": "25 Cents", "years": "2008", "metal": "Clad (Cu-Ni)", "diameter": "24.3 mm", "weight": "5.67 g", "key_dates": [], "notes": ""},
    {"title": "Alaska State Quarter",          "series": "State Quarter",    "country": "United States", "denomination": "25 Cents", "years": "2008", "metal": "Clad (Cu-Ni)", "diameter": "24.3 mm", "weight": "5.67 g", "key_dates": [], "notes": ""},
    {"title": "Hawaii State Quarter",          "series": "State Quarter",    "country": "United States", "denomination": "25 Cents", "years": "2008", "metal": "Clad (Cu-Ni)", "diameter": "24.3 mm", "weight": "5.67 g", "key_dates": [], "notes": ""},

    # ── DC & Territories Quarters (2009) ──────────────────────────────────────
    {"title": "District of Columbia Quarter",  "series": "DC & Territories", "country": "United States", "denomination": "25 Cents", "years": "2009", "metal": "Clad (Cu-Ni)", "diameter": "24.3 mm", "weight": "5.67 g", "key_dates": [], "notes": "Duke Ellington reverse."},
    {"title": "Puerto Rico Quarter",           "series": "DC & Territories", "country": "United States", "denomination": "25 Cents", "years": "2009", "metal": "Clad (Cu-Ni)", "diameter": "24.3 mm", "weight": "5.67 g", "key_dates": [], "notes": ""},
    {"title": "Guam Quarter",                  "series": "DC & Territories", "country": "United States", "denomination": "25 Cents", "years": "2009", "metal": "Clad (Cu-Ni)", "diameter": "24.3 mm", "weight": "5.67 g", "key_dates": [], "notes": ""},
    {"title": "American Samoa Quarter",        "series": "DC & Territories", "country": "United States", "denomination": "25 Cents", "years": "2009", "metal": "Clad (Cu-Ni)", "diameter": "24.3 mm", "weight": "5.67 g", "key_dates": [], "notes": ""},
    {"title": "US Virgin Islands Quarter",     "series": "DC & Territories", "country": "United States", "denomination": "25 Cents", "years": "2009", "metal": "Clad (Cu-Ni)", "diameter": "24.3 mm", "weight": "5.67 g", "key_dates": [], "notes": ""},
    {"title": "Northern Mariana Islands Quarter", "series": "DC & Territories", "country": "United States", "denomination": "25 Cents", "years": "2009", "metal": "Clad (Cu-Ni)", "diameter": "24.3 mm", "weight": "5.67 g", "key_dates": [], "notes": ""},

    # ── America the Beautiful Quarters (abbreviated) ──────────────────────────
    {"title": "America the Beautiful Quarters", "series": "ATB Quarter",    "country": "United States", "denomination": "25 Cents", "years": "2010-2021", "metal": "Clad (Cu-Ni)", "diameter": "24.3 mm", "weight": "5.67 g", "key_dates": ["2019-W West Point (first W-mint quarter for circulation)"], "notes": "56 designs depicting National Parks and Sites. 2019-W is the key."},

    # ── American Women Quarters ───────────────────────────────────────────────
    {"title": "American Women Quarters",       "series": "American Women",   "country": "United States", "denomination": "25 Cents", "years": "2022-2025", "metal": "Clad (Cu-Ni)", "diameter": "24.3 mm", "weight": "5.67 g", "key_dates": [], "notes": "20 designs honoring women. Includes Maya Angelou, Sally Ride, Wilma Mankiller, Nina Otero-Warren, Anna May Wong, and others."},

    # ── US Half Dollars ───────────────────────────────────────────────────────
    {"title": "Flowing Hair Half Dollar",      "series": "Half Dollar",      "country": "United States", "denomination": "50 Cents", "years": "1794-1795", "metal": "89.24% Silver",             "diameter": "32.5 mm", "weight": "13.48 g", "key_dates": ["1794"],                                               "notes": "First US half dollar."},
    {"title": "Draped Bust Half Dollar",       "series": "Half Dollar",      "country": "United States", "denomination": "50 Cents", "years": "1796-1807", "metal": "89.24% Silver",             "diameter": "32.5 mm", "weight": "13.48 g", "key_dates": ["1796", "1797"],                                       "notes": "1796/1797 have very low mintages."},
    {"title": "Capped Bust Half Dollar",       "series": "Half Dollar",      "country": "United States", "denomination": "50 Cents", "years": "1807-1839", "metal": "89.24% Silver",             "diameter": "32.5 mm", "weight": "13.48 g", "key_dates": ["1838-O", "1839-O"],                                   "notes": "1838-O is one of the rarest branch mint coins."},
    {"title": "Seated Liberty Half Dollar",    "series": "Half Dollar",      "country": "United States", "denomination": "50 Cents", "years": "1839-1891", "metal": "90% Silver",                "diameter": "30.6 mm", "weight": "12.44 g", "key_dates": ["1853-O No Arrows", "1878-S"],                         "notes": ""},
    {"title": "Barber Half Dollar",            "series": "Half Dollar",      "country": "United States", "denomination": "50 Cents", "years": "1892-1915", "metal": "90% Silver",                "diameter": "30.6 mm", "weight": "12.50 g", "key_dates": ["1892-O Micro O", "1914"],                             "notes": ""},
    {"title": "Walking Liberty Half Dollar",   "series": "Half Dollar",      "country": "United States", "denomination": "50 Cents", "years": "1916-1947", "metal": "90% Silver",                "diameter": "30.6 mm", "weight": "12.50 g", "key_dates": ["1916-S", "1921", "1921-D", "1921-S"],                 "notes": "Widely considered one of the most beautiful US coin designs. 1921-D has mintage of 208,000."},
    {"title": "Franklin Half Dollar",          "series": "Half Dollar",      "country": "United States", "denomination": "50 Cents", "years": "1948-1963", "metal": "90% Silver",                "diameter": "30.6 mm", "weight": "12.50 g", "key_dates": ["1949", "1955", "1955-P Double Die"],                  "notes": "Full Bell Lines (FBL) designation used in grading."},
    {"title": "Kennedy Half Dollar - Silver",  "series": "Half Dollar",      "country": "United States", "denomination": "50 Cents", "years": "1964",      "metal": "90% Silver",                "diameter": "30.6 mm", "weight": "12.50 g", "key_dates": ["1964 Accented Hair Proof"],                           "notes": "First year only in 90% silver. Issued as memorial to President Kennedy."},
    {"title": "Kennedy Half Dollar - 40% Silver", "series": "Half Dollar",   "country": "United States", "denomination": "50 Cents", "years": "1965-1970", "metal": "40% Silver",                "diameter": "30.6 mm", "weight": "11.50 g", "key_dates": ["1970-D"],                                             "notes": "1970-D was not released for circulation; only in Mint Sets."},
    {"title": "Kennedy Half Dollar - Clad",    "series": "Half Dollar",      "country": "United States", "denomination": "50 Cents", "years": "1971-present", "metal": "Clad (Cu-Ni)",           "diameter": "30.6 mm", "weight": "11.34 g", "key_dates": ["2014-W High Relief Gold", "2019-S Enhanced Reverse Proof"], "notes": "Rarely circulates. Common in rolls and bags. Special collector issues ongoing."},

    # ── US Dollars ────────────────────────────────────────────────────────────
    {"title": "Flowing Hair Dollar",           "series": "Dollar",           "country": "United States", "denomination": "$1",       "years": "1794-1795", "metal": "89.24% Silver",             "diameter": "39-40 mm","weight": "26.96 g", "key_dates": ["1794 (auction record $10M+)"],                        "notes": "First US silver dollar. 1794 is the most valuable US coin ever sold at auction."},
    {"title": "Draped Bust Dollar - Small Eagle", "series": "Dollar",        "country": "United States", "denomination": "$1",       "years": "1795-1798", "metal": "89.24% Silver",             "diameter": "39-40 mm","weight": "26.96 g", "key_dates": ["1796", "1797 9x7 Stars", "1798 Knob 9"],              "notes": ""},
    {"title": "Draped Bust Dollar - Heraldic Eagle", "series": "Dollar",     "country": "United States", "denomination": "$1",       "years": "1798-1804", "metal": "89.24% Silver",             "diameter": "39-40 mm","weight": "26.96 g", "key_dates": ["1804 (15 known, most valuable US coins)"],             "notes": "The 1804 dollar is called 'The King of American Coins'. Most are restrikes."},
    {"title": "Gobrecht Dollar",               "series": "Dollar",           "country": "United States", "denomination": "$1",       "years": "1836-1839", "metal": "90% Silver",                "diameter": "38.1 mm", "weight": "26.73 g", "key_dates": ["1836", "1838", "1839"],                               "notes": "Pattern/proof coinage. Flying eagle design."},
    {"title": "Seated Liberty Dollar",         "series": "Dollar",           "country": "United States", "denomination": "$1",       "years": "1840-1873", "metal": "90% Silver",                "diameter": "38.1 mm", "weight": "26.73 g", "key_dates": ["1851", "1852", "1858", "1870-S (9-12 known)"],        "notes": "1870-S is possibly unique; no record of authorized mintage."},
    {"title": "Trade Dollar",                  "series": "Dollar",           "country": "United States", "denomination": "$1",       "years": "1873-1885", "metal": "90% Silver",                "diameter": "38.1 mm", "weight": "27.22 g", "key_dates": ["1878-CC", "1884 (10 known)", "1885 (5 known)"],       "notes": "Designed for trade with Asia. Heavier than standard dollar. 1884/1885 proof-only issues are extreme rarities."},
    {"title": "Morgan Dollar",                 "series": "Dollar",           "country": "United States", "denomination": "$1",       "years": "1878-1921", "metal": "90% Silver",                "diameter": "38.1 mm", "weight": "26.73 g", "key_dates": ["1879-CC", "1889-CC", "1893-S", "1895 (proof only)", "1895-O", "1901", "1903-O", "1904-O"], "notes": "Most popular US silver coin series. 1893-S is the key; 1895 proof-only is unique. VAM varieties extensively catalogued."},
    {"title": "Peace Dollar",                  "series": "Dollar",           "country": "United States", "denomination": "$1",       "years": "1921-1935", "metal": "90% Silver",                "diameter": "38.1 mm", "weight": "26.73 g", "key_dates": ["1921 High Relief", "1927-D", "1927-S", "1928", "1934-S"], "notes": "Designed by Anthony de Francisci. 1928 is the key date (360,649 minted)."},
    {"title": "Eisenhower Dollar",             "series": "Dollar",           "country": "United States", "denomination": "$1",       "years": "1971-1978", "metal": "Clad / 40% Silver (collector)",  "diameter": "38.1 mm", "weight": "22.68 g", "key_dates": ["1972 Type 2", "1976 Bicentennial"],             "notes": "Clad for circulation; 40% silver collector versions. Bicentennial reverse 1975-1976."},
    {"title": "Susan B. Anthony Dollar",       "series": "Dollar",           "country": "United States", "denomination": "$1",       "years": "1979-1999", "metal": "Clad (Cu-Ni)",              "diameter": "26.5 mm", "weight": "8.1 g",   "key_dates": ["1979-P Wide Rim", "1981 (proof only)", "1999"],       "notes": "Often confused with a quarter. Revived for one year (1999) to meet vending machine demand."},
    {"title": "Sacagawea / Native American Dollar", "series": "Dollar",      "country": "United States", "denomination": "$1",       "years": "2000-present", "metal": "Brass (Mn-Brass)",          "diameter": "26.5 mm", "weight": "8.1 g",   "key_dates": ["2000-P Cheerios Dollar", "2000-P Wounded Eagle"],     "notes": "Golden color. Reverse designs change annually from 2009. Cheerios variety has enhanced tail feathers."},
    {"title": "Presidential Dollar",           "series": "Dollar",           "country": "United States", "denomination": "$1",       "years": "2007-2020", "metal": "Brass (Mn-Brass)",          "diameter": "26.5 mm", "weight": "8.1 g",   "key_dates": ["2007-P Washington Missing Edge Lettering", "2009-P Harrison No Edge Lettering"], "notes": "39 presidents honored. Edge lettering errors are popular varieties."},

    # ── US Gold ───────────────────────────────────────────────────────────────
    {"title": "Gold Dollar - Type I",          "series": "Gold Dollar",      "country": "United States", "denomination": "$1 Gold",  "years": "1849-1854", "metal": "Gold (90%)",                "diameter": "13 mm",   "weight": "1.672 g", "key_dates": ["1849-C Open Wreath", "1850-D"],                       "notes": "Smallest US coin by diameter. C and D mint issues are scarce."},
    {"title": "Gold Dollar - Type II",         "series": "Gold Dollar",      "country": "United States", "denomination": "$1 Gold",  "years": "1854-1856", "metal": "Gold (90%)",                "diameter": "15 mm",   "weight": "1.672 g", "key_dates": ["1854-D", "1855-C", "1855-D"],                         "notes": "Enlarged to address wear. All branch mint issues are rare."},
    {"title": "Gold Dollar - Type III",        "series": "Gold Dollar",      "country": "United States", "denomination": "$1 Gold",  "years": "1856-1889", "metal": "Gold (90%)",                "diameter": "15 mm",   "weight": "1.672 g", "key_dates": ["1861-D", "1875", "1876"],                             "notes": ""},
    {"title": "Quarter Eagle ($2.50 Gold)",    "series": "Gold",             "country": "United States", "denomination": "$2.50 Gold", "years": "1796-1929", "metal": "Gold (90%)",              "diameter": "18 mm",   "weight": "4.18 g",  "key_dates": ["1796 No Stars", "1808", "1841 (proof only)"],          "notes": "Various types across 130 years. Indian Head type (1908-1929) is popular."},
    {"title": "Three Dollar Gold Piece",       "series": "Gold",             "country": "United States", "denomination": "$3 Gold",  "years": "1854-1889", "metal": "Gold (90%)",                "diameter": "20.5 mm", "weight": "5.015 g", "key_dates": ["1854-D", "1870-S (1-2 known)", "1873 (proof only)", "1875 (proof only)"], "notes": "Unusual denomination; rarely encountered in circulation."},
    {"title": "Half Eagle ($5 Gold)",          "series": "Gold",             "country": "United States", "denomination": "$5 Gold",  "years": "1795-1929", "metal": "Gold (90%)",                "diameter": "21.6 mm", "weight": "8.359 g", "key_dates": ["1815", "1822 (3 known)", "1854-S"],                   "notes": "Longest-running US gold series. 1822 is one of the rarest US coins."},
    {"title": "Eagle ($10 Gold)",              "series": "Gold",             "country": "United States", "denomination": "$10 Gold", "years": "1795-1933", "metal": "Gold (90%)",                "diameter": "27 mm",   "weight": "16.718 g","key_dates": ["1798/7", "1804 Plain 4", "1933 (1 known, legal)"],    "notes": ""},
    {"title": "Double Eagle ($20 Gold) - Liberty Head", "series": "Gold",   "country": "United States", "denomination": "$20 Gold", "years": "1849-1907", "metal": "Gold (90%)",                "diameter": "34 mm",   "weight": "33.436 g","key_dates": ["1849 (unique)", "1861 Paquet Reverse", "1879-O", "1882", "1891"],  "notes": "Workhorse of US commerce. Many common dates available."},
    {"title": "Double Eagle ($20 Gold) - Saint-Gaudens", "series": "Gold",  "country": "United States", "denomination": "$20 Gold", "years": "1907-1933", "metal": "Gold (90%)",                "diameter": "34 mm",   "weight": "33.436 g","key_dates": ["1907 Ultra High Relief", "1927-D", "1930-S", "1933 (215 known, illegal to own)"], "notes": "Widely considered the most beautiful US coin. 1933 is the world's most valuable coin ($18.9M in 2021)."},

    # ── US Bullion ────────────────────────────────────────────────────────────
    {"title": "American Silver Eagle",         "series": "Bullion",          "country": "United States", "denomination": "$1",       "years": "1986-present", "metal": "99.9% Silver",           "diameter": "40.6 mm", "weight": "31.10 g (1 troy oz)", "key_dates": ["1995-W (proof only)", "2019-S Enhanced Reverse Proof", "2019-W Burnished", "2021 Type 1 & Type 2"], "notes": "Most popular silver bullion coin worldwide. Walking Liberty obverse."},
    {"title": "American Gold Eagle",           "series": "Bullion",          "country": "United States", "denomination": "$50 (1 oz)", "years": "1986-present", "metal": "91.67% Gold",          "diameter": "32.7 mm", "weight": "33.93 g", "key_dates": ["1991 Proof (low mintage)", "2006-W Reverse Proof"],  "notes": "Available in 1 oz, 1/2 oz, 1/4 oz, 1/10 oz denominations."},
    {"title": "American Gold Buffalo",         "series": "Bullion",          "country": "United States", "denomination": "$50 (1 oz)", "years": "2006-present", "metal": "99.99% Gold",          "diameter": "32.7 mm", "weight": "31.10 g", "key_dates": ["2008-W Reverse of 2007"],                             "notes": "First 24-karat gold coin struck by the US Mint. Buffalo Nickel design."},
    {"title": "American Platinum Eagle",       "series": "Bullion",          "country": "United States", "denomination": "$100 (1 oz)", "years": "1997-present", "metal": "99.95% Platinum",     "diameter": "32.7 mm", "weight": "31.10 g", "key_dates": [],                                                     "notes": "Reverse designs change annually for proof issues."},

    # ── Canadian Cents ────────────────────────────────────────────────────────
    {"title": "Canadian Large Cent",           "series": "Canadian Cent",    "country": "Canada",        "denomination": "1 Cent",   "years": "1858-1920", "metal": "Bronze / Copper",            "diameter": "25.4 mm", "weight": "5.67 g",  "key_dates": ["1858", "1859 Narrow 9", "1859 Double Punch 9", "1875-H", "1896 Obv. 3", "1920"],  "notes": "Victoria, Edward VII, and George V issues. 1858 is the first Canadian cent."},
    {"title": "Canadian Small Cent",           "series": "Canadian Cent",    "country": "Canada",        "denomination": "1 Cent",   "years": "1920-2012", "metal": "Bronze / Steel (1997-) / Copper-Plated Steel", "diameter": "19.05 mm", "weight": "3.24 g", "key_dates": ["1922", "1923", "1924", "1925", "1936 Dot (2 known)", "1948", "2012 (last year)"], "notes": "1936 dot cent is one of the most valuable Canadian coins. Cent discontinued in 2013."},

    # ── Canadian Five Cents ───────────────────────────────────────────────────
    {"title": "Canadian Five Cent - Silver",   "series": "Canadian Nickel",  "country": "Canada",        "denomination": "5 Cents",  "years": "1858-1921", "metal": "92.5% Silver",              "diameter": "15.5 mm", "weight": "1.162 g", "key_dates": ["1858", "1874-H", "1875-H", "1889", "1921 (2 known)"], "notes": "1921 is the rarest Canadian coin; most melted. 1858 is the first 5-cent piece."},
    {"title": "Canadian Five Cent - Nickel/Steel", "series": "Canadian Nickel", "country": "Canada",     "denomination": "5 Cents",  "years": "1922-present", "metal": "Nickel / Steel (2000-)", "diameter": "21.2 mm", "weight": "5 g / 3.95 g", "key_dates": ["1925", "1926 Far 6", "1947 Maple Leaf", "1965 Large Bead"], "notes": "Square (1942-1963) and round designs. Tombac brass used 1942-1943."},

    # ── Canadian Dimes ────────────────────────────────────────────────────────
    {"title": "Canadian Ten Cent - Silver",    "series": "Canadian Dime",    "country": "Canada",        "denomination": "10 Cents", "years": "1858-1967", "metal": "92.5% / 80% Silver",        "diameter": "18.03 mm","weight": "2.33 g",  "key_dates": ["1858", "1889", "1936 Dot (4 known)"],                 "notes": "Bluenose schooner on reverse 1937-2001 (with interruption)."},
    {"title": "Canadian Ten Cent - Nickel",    "series": "Canadian Dime",    "country": "Canada",        "denomination": "10 Cents", "years": "1968-present", "metal": "Nickel / Steel",          "diameter": "18.03 mm","weight": "2.07 g",  "key_dates": ["1968 Island reverse", "1969 Large Date"],             "notes": "Bluenose design continued."},

    # ── Canadian Quarters ─────────────────────────────────────────────────────
    {"title": "Canadian Quarter - Silver",     "series": "Canadian Quarter", "country": "Canada",        "denomination": "25 Cents", "years": "1870-1967", "metal": "92.5% / 80% Silver",        "diameter": "23.88 mm","weight": "5.81 g",  "key_dates": ["1875-H", "1889", "1906 Small Crown", "1936 Dot (2 known)"], "notes": "Caribou design introduced in 1937. 1936 dot is potentially unique."},
    {"title": "Canadian Quarter - Nickel",     "series": "Canadian Quarter", "country": "Canada",        "denomination": "25 Cents", "years": "1968-present", "metal": "Nickel / Steel",          "diameter": "23.88 mm","weight": "4.4 g",   "key_dates": ["1973 Large Bust RCMP", "2000 Millennium series"],      "notes": "Provincial/territorial designs and special issues common."},

    # ── Canadian Fifty Cents ──────────────────────────────────────────────────
    {"title": "Canadian Fifty Cent - Silver",  "series": "Canadian Half Dollar", "country": "Canada",    "denomination": "50 Cents", "years": "1870-1967", "metal": "92.5% / 80% Silver",        "diameter": "29.72 mm","weight": "11.62 g", "key_dates": ["1870 LC", "1871-H", "1890-H", "1921 (75 known)"],    "notes": "1921 is a major rarity; most were melted. Various Coat of Arms reverses."},
    {"title": "Canadian Fifty Cent - Nickel",  "series": "Canadian Half Dollar", "country": "Canada",    "denomination": "50 Cents", "years": "1968-present", "metal": "Nickel / Steel",          "diameter": "27.13 mm","weight": "6.9 g",   "key_dates": [],                                                     "notes": "Rarely circulates. Coat of Arms reverse."},

    # ── Canadian Dollars ──────────────────────────────────────────────────────
    {"title": "Canadian Silver Dollar - Voyageur", "series": "Canadian Dollar", "country": "Canada",     "denomination": "$1",       "years": "1935-1986", "metal": "80% Silver (1935-1967) / Nickel (1968-1986)", "diameter": "36.07 mm", "weight": "23.33 g (Ag)", "key_dates": ["1936 Dot (2 known)", "1947 Maple Leaf", "1948", "1952 No Water Lines", "1953 No Shoulder Fold"], "notes": "1935 is the first Canadian dollar (King George V). 1948 is the key date (18,780 minted). 1936 dot is potentially unique."},
    {"title": "Canadian Loonie ($1)",          "series": "Canadian Dollar",  "country": "Canada",        "denomination": "$1",       "years": "1987-present", "metal": "Aureate-Bronze (Nickel core)", "diameter": "26.5 mm", "weight": "6.27 g", "key_dates": ["1987 (first loonie)", "2004 Poppy", "2012 New Portrait"], "notes": "Common Loon on reverse. Name 'loonie' from the loon design. Replaced $1 banknote."},
    {"title": "Canadian Toonie ($2)",          "series": "Canadian Dollar",  "country": "Canada",        "denomination": "$2",       "years": "1996-present", "metal": "Bi-metallic (Al-Bronze / Nickel)", "diameter": "28 mm",  "weight": "7.3 g",   "key_dates": ["1996 (first toonie)", "2004 Bear mule error"],        "notes": "Polar bear on reverse. Bi-metallic coin. 'Toonie' from two-dollar + loonie."},

    # ── Canadian Gold & Bullion ───────────────────────────────────────────────
    {"title": "Canadian Gold Maple Leaf",      "series": "Canadian Bullion", "country": "Canada",        "denomination": "$50 (1 oz)", "years": "1979-present", "metal": "99.99% Gold",          "diameter": "30 mm",   "weight": "31.10 g", "key_dates": ["1979 (first)", "1982 (first 99.9% gold coin ever)"], "notes": "First coin in the world struck in 99.99% gold (from 1982). World's most trusted gold coin."},
    {"title": "Canadian Silver Maple Leaf",    "series": "Canadian Bullion", "country": "Canada",        "denomination": "$5 (1 oz)", "years": "1988-present", "metal": "99.99% Silver",          "diameter": "38 mm",   "weight": "31.10 g", "key_dates": ["1988 (first)", "1998 10th Anniversary"],              "notes": "99.99% fine silver. One of the world's most popular silver bullion coins."},
]


# ── Lookup helpers ────────────────────────────────────────────────────────────

def search(query: str, country: str = "All") -> List[Dict[str, Any]]:
    """Return catalog entries whose title, series, denomination or notes
    contain *query* (case-insensitive).  Optionally filter by country."""
    q = query.strip().lower()
    results = []
    for entry in CATALOG:
        if country != "All" and entry.get("country", "") != country:
            continue
        haystack = " ".join([
            entry.get("title", ""),
            entry.get("series", ""),
            entry.get("denomination", ""),
            entry.get("notes", ""),
            " ".join(entry.get("key_dates", [])),
        ]).lower()
        if not q or q in haystack:
            results.append(entry)
    return results


def to_coin_fields(entry: Dict[str, Any]) -> Dict[str, str]:
    """Convert a catalog entry to a dict of field names matching the
    ``coin`` item type in ``type_defs.py``, ready to fill the form."""
    return {
        "title":        entry.get("title", ""),
        "country":      entry.get("country", ""),
        "denomination": entry.get("denomination", ""),
        "metal":        entry.get("metal", ""),
        "diameter":     entry.get("diameter", ""),
        "weight":       entry.get("weight", ""),
    }
