"""Built-in item type definitions for Collector Catalog."""

BUILTIN_TYPES = [
    {
        "bib_key": "book",
        "display_name": "Book",
        "icon": "",
        "fields": [
            {"name": "title",     "label": "Title",       "type": "text",      "required": True,  "is_title": True},
            {"name": "author",    "label": "Author",      "type": "text",      "required": True,  "is_creator": True},
            {"name": "year",      "label": "Year",        "type": "text",      "is_year": True},
            {"name": "publisher", "label": "Publisher",   "type": "text"},
            {"name": "address",   "label": "Place",       "type": "text"},
            {"name": "edition",   "label": "Edition",     "type": "text"},
            {"name": "isbn",      "label": "ISBN",        "type": "text"},
            {"name": "pages",     "label": "Pages",       "type": "text"},
            {"name": "language",  "label": "Language",    "type": "text"},
            {"name": "series",    "label": "Series",      "type": "text"},
            {"name": "volume",    "label": "Volume",      "type": "text"},
            {"name": "genre",     "label": "Genre",       "type": "text"},
            {"name": "url",       "label": "URL",         "type": "text"},
            {"name": "abstract",  "label": "Abstract",    "type": "multiline"},
        ],
    },
    {
        "bib_key": "article",
        "display_name": "Article",
        "icon": "",
        "fields": [
            {"name": "title",    "label": "Title",    "type": "text", "required": True, "is_title": True},
            {"name": "author",   "label": "Author",   "type": "text", "required": True, "is_creator": True},
            {"name": "journal",  "label": "Journal",  "type": "text"},
            {"name": "year",     "label": "Year",     "type": "text", "is_year": True},
            {"name": "volume",   "label": "Volume",   "type": "text"},
            {"name": "number",   "label": "Number",   "type": "text"},
            {"name": "pages",    "label": "Pages",    "type": "text"},
            {"name": "doi",      "label": "DOI",      "type": "text"},
            {"name": "url",      "label": "URL",      "type": "text"},
            {"name": "abstract", "label": "Abstract", "type": "multiline"},
        ],
    },
    {
        "bib_key": "artwork",
        "display_name": "Artwork",
        "icon": "",
        "fields": [
            {"name": "title",          "label": "Title",          "type": "text", "required": True, "is_title": True},
            {"name": "artist",         "label": "Artist",         "type": "text", "required": True, "is_creator": True},
            {"name": "year",           "label": "Year / Date",    "type": "text", "is_year": True},
            {"name": "medium",         "label": "Medium",         "type": "text",
             "options": ["Oil on canvas", "Oil on panel", "Oil on board",
                         "Acrylic on canvas", "Watercolor", "Gouache", "Tempera",
                         "Fresco", "Pastel", "Charcoal", "Graphite / Pencil",
                         "Ink", "Pen and ink", "Mixed media", "Collage",
                         "Engraving", "Etching", "Lithograph", "Woodcut",
                         "Linocut", "Screenprint / Serigraph", "Mezzotint",
                         "Aquatint", "Drypoint", "Giclée print", "Photograph",
                         "Bronze", "Marble", "Wood carving", "Ceramic",
                         "Sculpture (mixed)", "Digital"]},
            {"name": "dimensions",     "label": "Dimensions",     "type": "text"},
            {"name": "period",         "label": "Period / Style", "type": "text",
             "options": ["Ancient", "Medieval", "Gothic", "Early Renaissance",
                         "Renaissance", "High Renaissance", "Mannerism",
                         "Baroque", "Rococo", "Neoclassicism", "Romanticism",
                         "Realism", "Pre-Raphaelite", "Impressionism",
                         "Post-Impressionism", "Pointillism", "Symbolism",
                         "Art Nouveau", "Fauvism", "Expressionism", "Cubism",
                         "Futurism", "Dada", "Surrealism", "Art Deco",
                         "Abstract Expressionism", "Pop Art", "Minimalism",
                         "Op Art", "Conceptual Art", "Contemporary", "Folk / Naïve",
                         "Street Art"]},
            {"name": "school",         "label": "School",         "type": "text",
             "options": ["Italian", "Florentine", "Venetian", "Sienese", "Roman",
                         "Dutch", "Flemish", "German", "French", "Spanish",
                         "English / British", "American", "Russian", "Northern European",
                         "Hudson River School", "Barbizon School", "Bauhaus",
                         "Ashcan School", "Japanese (Ukiyo-e)", "Chinese", "Other"]},
            {"name": "subject",        "label": "Subject",        "type": "text",
             "options": ["Portrait", "Self-Portrait", "Landscape", "Seascape",
                         "Cityscape", "Still Life", "Genre Scene", "Historical",
                         "Mythological", "Religious", "Allegory", "Nude",
                         "Animal", "Abstract", "Floral", "Interior", "Nautical"]},
            {"name": "collection",     "label": "Collection",     "type": "text"},
            {"name": "location",       "label": "Location",       "type": "text"},
            {"name": "condition",      "label": "Condition",      "type": "text"},
            {"name": "catalog_number", "label": "Catalog #",      "type": "text"},
            {"name": "provenance",     "label": "Provenance",     "type": "multiline"},
            {"name": "inscription",    "label": "Inscription",    "type": "text"},
        ],
    },
    {
        "bib_key": "document",
        "display_name": "Historical Document",
        "icon": "",
        "fields": [
            {"name": "title",               "label": "Title",           "type": "text", "required": True, "is_title": True},
            {"name": "author",              "label": "Author / Creator","type": "text", "is_creator": True},
            {"name": "date",                "label": "Date",            "type": "text", "is_year": True},
            {"name": "document_type",       "label": "Document Type",   "type": "text"},
            {"name": "language",            "label": "Language",        "type": "text"},
            {"name": "origin",              "label": "Origin",          "type": "text"},
            {"name": "dimensions",          "label": "Dimensions",      "type": "text"},
            {"name": "material",            "label": "Material",        "type": "text"},
            {"name": "condition",           "label": "Condition",       "type": "text"},
            {"name": "institution",         "label": "Institution",     "type": "text"},
            {"name": "catalog_number",      "label": "Catalog #",       "type": "text"},
            {"name": "content_description", "label": "Description",     "type": "multiline"},
            {"name": "transcription",       "label": "Transcription",   "type": "multiline"},
        ],
    },
    {
        "bib_key": "vinyl",
        "display_name": "Vinyl Record",
        "icon": "",
        "fields": [
            {"name": "title",          "label": "Album Title", "type": "text", "required": True, "is_title": True},
            {"name": "artist",         "label": "Artist",      "type": "text", "required": True, "is_creator": True},
            {"name": "year",           "label": "Year",        "type": "text", "is_year": True},
            {"name": "label",          "label": "Label",       "type": "text"},
            {"name": "catalog_number", "label": "Catalog #",   "type": "text"},
            {"name": "format",         "label": "Format",      "type": "text",
             "options": ["LP", "12\" Single", "10\"", "7\" Single", "EP", "Double LP",
                         "Box Set", "Picture Disc", "Coloured Vinyl", "78 RPM", "45 RPM",
                         "33 1/3 RPM", "Test Pressing", "Promo"]},
            {"name": "pressing",       "label": "Pressing",    "type": "text",
             "options": ["First Pressing", "Original", "Reissue", "Repress",
                         "Limited Edition", "Audiophile", "Mono", "Stereo"]},
            {"name": "country",        "label": "Country",     "type": "text"},
            {"name": "genre",          "label": "Genre",       "type": "text"},
            {"name": "condition",      "label": "Condition",   "type": "text",
             "options": ["Mint (M)", "Near Mint (NM)", "Very Good Plus (VG+)",
                         "Very Good (VG)", "Good Plus (G+)", "Good (G)", "Fair (F)",
                         "Poor (P)"]},
            {"name": "tracklist",      "label": "Tracklist",   "type": "multiline"},
        ],
    },
    {
        "bib_key": "comic",
        "display_name": "Comic / Manga",
        "icon": "",
        "fields": [
            {"name": "title",     "label": "Series Title", "type": "text", "required": True, "is_title": True},
            {"name": "issue",     "label": "Issue #",      "type": "text"},
            {"name": "writer",    "label": "Writer",       "type": "text", "is_creator": True},
            {"name": "artist",    "label": "Artist",       "type": "text"},
            {"name": "year",      "label": "Year",         "type": "text", "is_year": True},
            {"name": "publisher", "label": "Publisher",    "type": "text"},
            {"name": "variant",   "label": "Variant",      "type": "text"},
            {"name": "condition", "label": "Condition",    "type": "text",
             "options": ["Mint", "Near Mint", "Very Fine", "Fine", "Very Good",
                         "Good", "Fair", "Poor"]},
            {"name": "grade",     "label": "Grade",        "type": "text"},
            {"name": "grader",    "label": "Grading Co.",  "type": "text",
             "options": ["CGC", "CBCS", "PGX", "Raw / Ungraded"]},
            {"name": "print_run", "label": "Print Run",    "type": "text"},
            {"name": "upc",       "label": "UPC",          "type": "text"},
        ],
    },
    {
        "bib_key": "tradingcard",
        "display_name": "Trading Card",
        "icon": "",
        "fields": [
            {"name": "title",       "label": "Card Name",    "type": "text", "required": True, "is_title": True},
            {"name": "player",      "label": "Player / Char","type": "text", "is_creator": True},
            {"name": "year",        "label": "Year",         "type": "text", "is_year": True},
            {"name": "game",        "label": "Game / Sport", "type": "text"},
            {"name": "set_name",    "label": "Set",          "type": "text"},
            {"name": "card_number", "label": "Card #",       "type": "text"},
            {"name": "rarity",      "label": "Rarity",       "type": "text"},
            {"name": "condition",   "label": "Condition",    "type": "text"},
            {"name": "grade",       "label": "Grade",        "type": "text"},
            {"name": "grader",      "label": "Grading Co.",  "type": "text"},
            {"name": "print_run",   "label": "Print Run",    "type": "text"},
            {"name": "language",    "label": "Language",     "type": "text"},
        ],
    },
    {
        "bib_key": "coin",
        "display_name": "Coin",
        "icon": "",
        "fields": [
            {"name": "title",          "label": "Name",           "type": "text", "required": True, "is_title": True},
            {"name": "country",        "label": "Country",        "type": "text", "is_creator": True},
            {"name": "year",           "label": "Year",           "type": "text", "is_year": True},
            {"name": "denomination",   "label": "Denomination",   "type": "text"},
            {"name": "mint",           "label": "Mint",           "type": "text"},
            {"name": "mint_mark",      "label": "Mint Mark",      "type": "text",
             "options": ["P (Philadelphia)", "D (Denver)", "S (San Francisco)",
                         "W (West Point)", "CC (Carson City)", "O (New Orleans)",
                         "C (Charlotte)", "D (Dahlonega)", "None / No Mint Mark"]},
            {"name": "metal",          "label": "Metal",          "type": "text",
             "options": ["Gold", "Silver", "Platinum", "Palladium", "Copper",
                         "Bronze", "Brass", "Nickel", "Copper-Nickel",
                         "Clad (Cu-Ni)", "Steel", "Zinc", "Aluminum",
                         "Bi-Metallic", "Electrum", "Billon"]},
            {"name": "strike",         "label": "Strike Type",    "type": "text",
             "options": ["Business / Circulation", "Proof", "Proof-Like",
                         "Deep Cameo / Ultra Cameo", "Cameo", "Matte Proof",
                         "Specimen", "Pattern", "Commemorative", "Bullion"]},
            {"name": "diameter",       "label": "Diameter",       "type": "text"},
            {"name": "weight",         "label": "Weight",         "type": "text"},
            {"name": "grade",          "label": "Grade",          "type": "text",
             # Sheldon 70-point scale (circulated + uncirculated + proof)
             "options": ["MS-70", "MS-69", "MS-68", "MS-67", "MS-66", "MS-65",
                         "MS-64", "MS-63", "MS-62", "MS-61", "MS-60",
                         "AU-58", "AU-55", "AU-53", "AU-50",
                         "XF-45", "XF-40", "VF-35", "VF-30", "VF-25", "VF-20",
                         "F-15", "F-12", "VG-10", "VG-8", "G-6", "G-4",
                         "AG-3", "FR-2", "PO-1",
                         "PR-70", "PR-69", "PR-68", "PR-67", "PR-66", "PR-65",
                         "PR-64", "PR-63", "PR-62", "PR-60",
                         "Ungraded / Raw"]},
            {"name": "certification",  "label": "Certification",  "type": "text",
             "options": ["PCGS", "NGC", "ANACS", "ICG", "PMG", "SEGS",
                         "CACG", "Raw / Uncertified"]},
            {"name": "cert_number",    "label": "Cert #",         "type": "text"},
            {"name": "variety",        "label": "Variety",        "type": "text"},
            {"name": "catalog_number", "label": "KM / Cat #",     "type": "text"},
        ],
    },
    {
        "bib_key": "stamp",
        "display_name": "Stamp",
        "icon": "",
        "fields": [
            {"name": "title",          "label": "Name",          "type": "text", "required": True, "is_title": True},
            {"name": "country",        "label": "Country",       "type": "text", "is_creator": True},
            {"name": "year",           "label": "Year Issued",   "type": "text", "is_year": True},
            {"name": "denomination",   "label": "Denomination",  "type": "text"},
            {"name": "catalog_number", "label": "Scott / Cat #", "type": "text"},
            {"name": "color",          "label": "Color",         "type": "text"},
            {"name": "perforation",    "label": "Perforation",   "type": "text"},
            {"name": "watermark",      "label": "Watermark",     "type": "text"},
            {"name": "condition",      "label": "Condition",     "type": "text"},
            {"name": "grade",          "label": "Grade",         "type": "text"},
            {"name": "gum",            "label": "Gum Condition", "type": "text"},
            {"name": "cancel",         "label": "Cancel",        "type": "text"},
            {"name": "print_quantity", "label": "Print Qty",     "type": "text"},
        ],
    },
    {
        "bib_key": "camera",
        "display_name": "Camera",
        "icon": "",
        "fields": [
            {"name": "title",     "label": "Model",         "type": "text", "required": True, "is_title": True},
            {"name": "make",      "label": "Make",          "type": "text", "is_creator": True,
             "options": ["Nikon", "Canon", "Sony", "Leica", "Fujifilm", "Olympus", "OM System",
                         "Panasonic", "Pentax", "Hasselblad", "Mamiya", "Rolleiflex", "Contax",
                         "Minolta", "Konica", "Yashica", "Voigtländer", "Sigma", "Ricoh",
                         "Phase One", "Polaroid", "Kodak", "Bronica", "Linhof", "Plaubel"]},
            {"name": "year",      "label": "Year",          "type": "text", "is_year": True},
            {"name": "type",      "label": "Camera Type",   "type": "text",
             "options": ["DSLR", "Mirrorless", "Rangefinder", "SLR (film)", "TLR",
                         "Point & Shoot", "Medium Format", "Large Format", "Instant", "Cinema"]},
            {"name": "format",    "label": "Format",        "type": "text",
             "options": ["35mm Full Frame", "APS-C", "Micro Four Thirds", "Medium Format",
                         "Large Format 4x5", "Large Format 8x10", "120 Film", "35mm Film",
                         "110 Film", "Instant", "1\""]},
            {"name": "mount",     "label": "Lens Mount",    "type": "text",
             "options": ["Nikon F", "Nikon Z", "Canon EF", "Canon RF", "Canon FD",
                         "Sony E", "Sony A", "Leica M", "Leica L", "Leica R",
                         "Fujifilm X", "Fujifilm G", "Micro Four Thirds", "Pentax K",
                         "M42", "Hasselblad V", "Hasselblad H", "Mamiya RB", "Mamiya RZ",
                         "Contax/Yashica", "Olympus OM", "Minolta MD", "Bronica ETR"]},
            {"name": "serial_number", "label": "Serial #",  "type": "text"},
            {"name": "shutter_count", "label": "Shutter Count", "type": "text"},
            {"name": "condition", "label": "Condition",     "type": "text",
             "options": ["Mint", "Near Mint", "Excellent+", "Excellent", "Very Good",
                         "Good", "Fair", "For Parts / Not Working"]},
            {"name": "purchase_date",  "label": "Purchase Date",  "type": "text"},
            {"name": "purchase_price", "label": "Purchase Price", "type": "text"},
            {"name": "current_value",  "label": "Current Value",  "type": "text"},
            {"name": "notes",     "label": "Notes",         "type": "multiline"},
        ],
    },
    {
        "bib_key": "lens",
        "display_name": "Camera Lens",
        "icon": "",
        "fields": [
            {"name": "title",       "label": "Model",       "type": "text", "required": True, "is_title": True},
            {"name": "make",        "label": "Make",        "type": "text", "is_creator": True,
             "options": ["Nikon", "Nikkor", "Canon", "Sony", "Sony G Master", "Zeiss",
                         "Carl Zeiss", "Leica", "Voigtländer", "Sigma", "Tamron", "Tokina",
                         "Fujifilm", "Fujinon", "Olympus", "M.Zuiko", "Panasonic", "Lumix",
                         "Pentax", "Mamiya", "Hasselblad", "Rokinon", "Samyang", "7Artisans",
                         "Laowa", "Cooke", "Schneider", "Rodenstock"]},
            {"name": "mount",       "label": "Mount",       "type": "text",
             "options": ["Nikon F", "Nikon Z", "Canon EF", "Canon EF-S", "Canon RF", "Canon FD",
                         "Sony E", "Sony FE", "Sony A", "Leica M", "Leica L", "Leica R",
                         "Fujifilm X", "Fujifilm G", "Micro Four Thirds", "Pentax K",
                         "M42", "Hasselblad V", "Hasselblad H", "Mamiya RB", "Mamiya RZ",
                         "Olympus OM", "Minolta MD", "Contax/Yashica", "T2"]},
            {"name": "focal_length","label": "Focal Length","type": "text"},
            {"name": "max_aperture","label": "Max Aperture","type": "text",
             "options": ["f/0.95", "f/1.0", "f/1.2", "f/1.4", "f/1.8", "f/2.0",
                         "f/2.5", "f/2.8", "f/3.5", "f/4.0", "f/4.5", "f/5.6",
                         "f/6.3", "f/8.0"]},
            {"name": "lens_type",   "label": "Lens Type",   "type": "text",
             "options": ["Prime", "Zoom", "Macro", "Tilt-Shift", "Fisheye",
                         "Telephoto", "Wide", "Ultra-Wide", "Standard", "Portrait",
                         "Cine", "Mirror / Reflex"]},
            {"name": "format_coverage", "label": "Image Circle", "type": "text",
             "options": ["Full Frame", "APS-C", "Micro Four Thirds", "Medium Format",
                         "Large Format", "Super 35", "1\""]},
            {"name": "year",        "label": "Year / Version", "type": "text", "is_year": True},
            {"name": "serial_number", "label": "Serial #",  "type": "text"},
            {"name": "filter_size", "label": "Filter Size", "type": "text"},
            {"name": "condition",   "label": "Condition",   "type": "text",
             "options": ["Mint", "Near Mint", "Excellent+", "Excellent", "Very Good",
                         "Good", "Fair", "For Parts / Not Working"]},
            {"name": "glass_condition", "label": "Glass Condition", "type": "text",
             "options": ["Pristine", "Clear", "Minor Dust", "Light Haze", "Heavy Haze",
                         "Fungus", "Scratches", "Separation"]},
            {"name": "purchase_date",  "label": "Purchase Date",  "type": "text"},
            {"name": "purchase_price", "label": "Purchase Price", "type": "text"},
            {"name": "current_value",  "label": "Current Value",  "type": "text"},
            {"name": "notes",       "label": "Notes",       "type": "multiline"},
        ],
    },
    {
        "bib_key": "videogame",
        "display_name": "Video Game",
        "icon": "",
        "fields": [
            {"name": "title",          "label": "Title",        "type": "text", "required": True, "is_title": True},
            {"name": "console",        "label": "Console",      "type": "text", "is_creator": True,
             "options": [
                # Nintendo
                "Nintendo Entertainment System", "Super Nintendo", "Nintendo 64",
                "GameCube", "Wii", "Wii U", "Switch", "Switch 2",
                "Game Boy", "Game Boy Color", "Game Boy Advance",
                "Nintendo DS", "Nintendo 3DS",
                "Virtual Boy",
                # Sega
                "Sega Master System", "Sega Genesis", "Sega CD", "Sega 32X",
                "Sega Saturn", "Sega Dreamcast", "Sega Game Gear",
                # Sony
                "PlayStation", "PlayStation 2", "PlayStation 3",
                "PlayStation 4", "PlayStation 5", "PSP", "PS Vita",
                # Microsoft
                "Xbox", "Xbox 360", "Xbox One", "Xbox Series X/S",
                # Atari & retro
                "Atari 2600", "Atari 5200", "Atari 7800", "Atari Jaguar",
                "Atari Lynx", "ColecoVision", "Intellivision", "Neo Geo",
                "Neo Geo Pocket", "TurboGrafx-16", "PC Engine", "3DO",
                # PC / other
                "PC", "Mac", "Amiga", "Commodore 64", "MSX", "ZX Spectrum",
                # Arcade
                "Arcade",
             ]},
            {"name": "publisher",      "label": "Publisher",    "type": "text"},
            {"name": "developer",      "label": "Developer",    "type": "text"},
            {"name": "year",           "label": "Year",         "type": "text", "is_year": True},
            {"name": "genre",          "label": "Genre",        "type": "text",
             "options": ["Action", "Adventure", "RPG", "JRPG", "Platformer",
                         "Shooter", "FPS", "Fighting", "Racing", "Sports",
                         "Puzzle", "Strategy", "Simulation", "Survival",
                         "Horror", "Stealth", "Music / Rhythm", "Party",
                         "Educational", "Beat 'em up", "Visual Novel",
                         "MMO", "Sandbox", "Roguelike"]},
            {"name": "region",         "label": "Region",       "type": "text",
             "options": ["NTSC-U (North America)", "PAL (Europe)",
                         "NTSC-J (Japan)", "Worldwide", "Asia",
                         "South America (Brazil/Tectoy)", "Other"]},
            {"name": "completeness",   "label": "Completeness", "type": "text",
             "options": ["CIB (Complete in Box)", "Sealed / New",
                         "Box + Manual + Cart", "Box + Cart", "Manual + Cart",
                         "Cart / Disc Only (Loose)", "Manual Only", "Box Only",
                         "Graded"]},
            {"name": "condition",      "label": "Condition",    "type": "text",
             "options": ["Sealed", "Mint", "Near Mint", "Excellent",
                         "Very Good", "Good", "Fair", "Poor",
                         "For Parts / Not Working"]},
            {"name": "grade",          "label": "Grade",        "type": "text"},
            {"name": "grader",         "label": "Grading Co.",  "type": "text",
             "options": ["WATA", "VGA", "CGC Video Games", "Raw / Ungraded"]},
            {"name": "media",          "label": "Media",        "type": "text",
             "options": ["Cartridge", "CD", "DVD", "Blu-ray", "UMD",
                         "Floppy Disk", "Tape", "Digital", "Download Code"]},
            {"name": "upc",            "label": "UPC / Barcode","type": "text"},
            {"name": "catalog_number", "label": "Catalog #",    "type": "text"},
            {"name": "serial_number",  "label": "Serial #",     "type": "text"},
            {"name": "purchase_date",  "label": "Purchase Date","type": "text"},
            {"name": "purchase_price", "label": "Purchase Price","type": "text"},
            {"name": "loose_price",    "label": "Loose Price",  "type": "text"},
            {"name": "cib_price",      "label": "CIB Price",    "type": "text"},
            {"name": "new_price",      "label": "New / Sealed Price", "type": "text"},
            {"name": "current_value",  "label": "Current Value","type": "text"},
            {"name": "pricecharting_id", "label": "PriceCharting ID", "type": "text"},
            {"name": "pricecharting_url","label": "PriceCharting URL","type": "text"},
            {"name": "description",    "label": "Description",  "type": "multiline"},
        ],
    },
    {
        "bib_key": "console",
        "display_name": "Video Game Console",
        "icon": "",
        "fields": [
            {"name": "title",          "label": "Model",        "type": "text", "required": True, "is_title": True},
            {"name": "manufacturer",   "label": "Manufacturer", "type": "text", "is_creator": True,
             "options": ["Nintendo", "Sony", "Microsoft", "Sega", "Atari",
                         "SNK", "NEC", "Coleco", "Mattel", "Panasonic",
                         "Philips", "Commodore", "3DO Company", "Bandai"]},
            {"name": "generation",     "label": "Generation",   "type": "text",
             "options": ["1st Generation", "2nd Generation", "3rd Generation",
                         "4th Generation", "5th Generation", "6th Generation",
                         "7th Generation", "8th Generation", "9th Generation",
                         "Handheld"]},
            {"name": "year",           "label": "Year",         "type": "text", "is_year": True},
            {"name": "region",         "label": "Region",       "type": "text",
             "options": ["NTSC-U (North America)", "PAL (Europe)",
                         "NTSC-J (Japan)", "Worldwide", "Other"]},
            {"name": "revision",       "label": "Model / Revision", "type": "text"},
            {"name": "color",          "label": "Color / Variant", "type": "text"},
            {"name": "storage",        "label": "Storage",      "type": "text"},
            {"name": "serial_number",  "label": "Serial #",     "type": "text"},
            {"name": "completeness",   "label": "Completeness", "type": "text",
             "options": ["CIB (Complete in Box)", "Sealed / New",
                         "Console + Controller + Cables", "Console + Cables",
                         "Console Only", "Box Only", "Bundle / Limited Edition"]},
            {"name": "accessories",    "label": "Accessories",  "type": "multiline"},
            {"name": "condition",      "label": "Condition",    "type": "text",
             "options": ["Sealed", "Mint", "Near Mint", "Excellent",
                         "Very Good", "Good", "Fair", "Poor",
                         "For Parts / Not Working"]},
            {"name": "modifications",  "label": "Modifications", "type": "text",
             "options": ["None / Stock", "Region-Free Mod", "Modchip",
                         "HDMI Mod", "RGB Mod", "Optical Drive Emulator (ODE)",
                         "SSD Upgrade", "Recapped", "Custom Firmware",
                         "Backlit Screen Mod"]},
            {"name": "purchase_date",  "label": "Purchase Date", "type": "text"},
            {"name": "purchase_price", "label": "Purchase Price","type": "text"},
            {"name": "current_value",  "label": "Current Value", "type": "text"},
            {"name": "pricecharting_id", "label": "PriceCharting ID", "type": "text"},
            {"name": "description",    "label": "Description",  "type": "multiline"},
        ],
    },
    {
        "bib_key": "computer",
        "display_name": "Computer / Tech",
        "icon": "",
        "fields": [
            {"name": "title",          "label": "Model",        "type": "text", "required": True, "is_title": True},
            {"name": "manufacturer",   "label": "Manufacturer", "type": "text", "is_creator": True,
             "options": ["Apple", "IBM", "Dell", "HP", "Hewlett-Packard", "Compaq",
                         "Lenovo", "ThinkPad", "ASUS", "Acer", "MSI", "Microsoft",
                         "Sony", "Toshiba", "Samsung", "LG", "Razer", "Gateway",
                         "Commodore", "Atari", "Amiga", "Tandy / RadioShack",
                         "Sun Microsystems", "Silicon Graphics (SGI)", "NeXT",
                         "DEC", "Packard Bell", "Framework", "System76",
                         "Raspberry Pi", "Custom Build", "Other"]},
            {"name": "form_factor",    "label": "Form Factor",  "type": "text",
             "options": ["Laptop", "Desktop Tower", "Small Form Factor", "All-in-One",
                         "Mini PC", "Workstation", "Server", "Rackmount",
                         "Tablet", "2-in-1 Convertible", "Netbook", "Handheld PC",
                         "Single-Board Computer", "Vintage Microcomputer",
                         "Mainframe / Terminal"]},
            {"name": "category",       "label": "Category",     "type": "text",
             "options": ["Complete System", "Laptop", "Desktop", "Monitor",
                         "Keyboard", "Mouse", "CPU / Processor", "Motherboard",
                         "GPU / Graphics Card", "RAM / Memory", "Storage Drive",
                         "Power Supply", "Sound Card", "Network Card",
                         "Expansion Card", "Peripheral", "Software", "Accessory",
                         "Cable / Adapter", "Other Component"]},
            {"name": "year",           "label": "Year",         "type": "text", "is_year": True},
            {"name": "model_number",   "label": "Model / Part #","type": "text"},
            {"name": "serial_number",  "label": "Serial #",     "type": "text"},
            {"name": "operating_system","label": "Operating System", "type": "text",
             "options": ["macOS", "Mac OS X", "Classic Mac OS", "System 7",
                         "Windows 11", "Windows 10", "Windows 7", "Windows XP",
                         "Windows 98", "Windows 95", "MS-DOS", "Linux", "Ubuntu",
                         "Chrome OS", "Unix", "BSD", "AmigaOS", "BeOS",
                         "Commodore BASIC", "None / Bare"]},
            {"name": "cpu",            "label": "CPU / Processor","type": "text"},
            {"name": "ram",            "label": "RAM",          "type": "text"},
            {"name": "storage",        "label": "Storage",      "type": "text"},
            {"name": "gpu",            "label": "Graphics",     "type": "text"},
            {"name": "screen_size",    "label": "Screen Size",  "type": "text"},
            {"name": "condition",      "label": "Condition",    "type": "text",
             "options": ["Sealed / New", "Mint", "Near Mint", "Excellent",
                         "Very Good", "Good", "Fair", "Poor",
                         "Refurbished", "For Parts / Not Working"]},
            {"name": "working_status", "label": "Working Status","type": "text",
             "options": ["Fully Working", "Partially Working", "Untested",
                         "Boots / No OS", "Not Working", "Restored", "Recapped"]},
            {"name": "completeness",   "label": "Completeness", "type": "text",
             "options": ["CIB (Complete in Box)", "Sealed", "With Original Box",
                         "Unit + Accessories", "Unit Only", "Bare Component"]},
            {"name": "purchase_date",  "label": "Purchase Date","type": "text"},
            {"name": "purchase_price", "label": "Purchase Price","type": "text"},
            {"name": "current_value",  "label": "Current Value","type": "text"},
            {"name": "description",    "label": "Description",  "type": "multiline"},
        ],
    },
    {
        "bib_key": "misc",
        "display_name": "Miscellaneous",
        "icon": "",
        "fields": [
            {"name": "title",       "label": "Name",        "type": "text", "required": True, "is_title": True},
            {"name": "creator",     "label": "Creator",     "type": "text", "is_creator": True},
            {"name": "year",        "label": "Year",        "type": "text", "is_year": True},
            {"name": "item_type",   "label": "Type",        "type": "text"},
            {"name": "description", "label": "Description", "type": "multiline"},
            {"name": "condition",   "label": "Condition",   "type": "text"},
            {"name": "origin",      "label": "Origin",      "type": "text"},
            {"name": "dimensions",  "label": "Dimensions",  "type": "text"},
            {"name": "material",    "label": "Material",    "type": "text"},
        ],
    },
]


def get_field_attr(fields, attr, default=None):
    """Return the field name that has the given boolean attribute set."""
    for f in fields:
        if f.get(attr):
            return f["name"]
    return default
